force-app/main/default/objects/AR_Surg_Accounts_Receivable__c/AR_Surg_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <label>Surgical Accounts Receivable</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Surgical Accounts Receivables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_Surg_Accounts_Receivable__c/fields/Injection_Status__c.field-meta.xml
<CustomField>
    <fullName>Injection_Status__c</fullName>
    <label>Injection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>UNB</fullName>
            </value>
            <value>
                <fullName>INP</fullName>
            </value>
            <value>
                <fullName>REP</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>R-PLN</fullName>
            </value>
            <value>
                <fullName>PLN-REF</fullName>
            </value>
            <value>
                <fullName>PLN-FIN</fullName>
            </value>
            <value>
                <fullName>NCOF</fullName>
            </value>
            <value>
                <fullName>SCS</fullName>
            </value>
            <value>
                <fullName>RSC</fullName>
            </value>
            <value>
                <fullName>OPN</fullName>
            </value>
            <value>
                <fullName>H-ZEL</fullName>
            </value>
            <value>
                <fullName>RUL</fullName>
            </value>
            <value>
                <fullName>PAA</fullName>
            </value>
            <value>
                <fullName>PPR</fullName>
            </value>
            <value>
                <fullName>PSR</fullName>
            </value>
            <value>
                <fullName>FES</fullName>
            </value>
            <value>
                <fullName>ARB</fullName>
            </value>
            <value>
                <fullName>LOP</fullName>
            </value>
            <value>
                <fullName>LOP-N</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>LVM</fullName>
            </value>
            <value>
                <fullName>CSP</fullName>
            </value>
            <value>
                <fullName>FTP</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>SPB</fullName>
            </value>
            <value>
                <fullName>DME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARSurgRequestDashboardController.cls
/**
* @File Name : ARSurgRequestDashboardController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 30, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 30, 2025 |   | Initial Version
**/

public class ARSurgRequestDashboardController {
   @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getRequestCounts() {
        Id userId = UserInfo.getUserId();
        Map<String, Integer> counts = new Map<String, Integer>();

        // New Requests: CreatedDate = TODAY, assigned to me
        Integer newRequests = [
            SELECT COUNT() FROM AR_Surg_Accounts_Receivable__c 
            WHERE OwnerId = :userId AND CreatedDate = TODAY
        ];

        // Previous Requests: Assigned to me, CreatedDate < TODAY, Injection_Status__c = null
        Integer previousRequests = [
            SELECT COUNT() FROM AR_Surg_Accounts_Receivable__c 
            WHERE OwnerId = :userId 
            AND CreatedDate < TODAY 
            AND Injection_Status__c = NULL
        ];

        // Inventory = New + Previous
        Integer inventory = newRequests + previousRequests;

        // Completed Requests: Assigned to me, Injection_Status__c = 'ACC'
        Integer completedRequests = [
            SELECT COUNT() FROM AR_Surg_Accounts_Receivable__c 
            WHERE OwnerId = :userId 
            AND Injection_Status__c = 'ACC'
        ];

        // Put results in map
        counts.put('inventory', inventory);
        counts.put('newRequests', newRequests);
        counts.put('previousRequests', previousRequests);
        counts.put('completedRequests', completedRequests);

        return counts;
    }
}