force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Acupuncture__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Acupuncture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Acupuncture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_DME__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_DME__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for DME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_OT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for OT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Procedures__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Procedures</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_PT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_PT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for PT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_Out_Of_Network_Provider_Treat_Here__c.field-meta.xml
<CustomField>
    <fullName>Can_Out_Of_Network_Provider_Treat_Here__c</fullName>
    <label>Can Out Of Network Provider Treat Here</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_patient_treat_at_ASC__c.field-meta.xml
<CustomField>
    <fullName>Can_patient_treat_at_ASC__c</fullName>
    <label>Can Patient Treat at ASC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_we_buy_and_bill_injection_codes__c.field-meta.xml
<CustomField>
    <fullName>Can_we_buy_and_bill_injection_codes__c</fullName>
    <label>Can we buy and bill injection codes?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_Combined__c</fullName>
    <label>Chiro Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claims_Address__c.field-meta.xml
<CustomField>
    <fullName>Claims_Address__c</fullName>
    <label>Claims Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Conservative_Modalities_Combined_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Conservative_Modalities_Combined_Per_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conservative Modalities Combined Per Day</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Count_As_1_Or_2_Visits__c.field-meta.xml
<CustomField>
    <fullName>Count_As_1_Or_2_Visits__c</fullName>
    <label>Count As 1 Or 2 Visits</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Date_of_Accident__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Accident__c</fullName>
    <label>Date of Accident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Benefits_Notes__c.field-meta.xml
<CustomField>
    <fullName>DME_Benefits_Notes__c</fullName>
    <label>DME Benefits Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Diagnosis_Codes__c.field-meta.xml
<CustomField>
    <fullName>DME_Diagnosis_Codes__c</fullName>
    <label>DME Diagnosis Codes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Diagnosis_Dependent__c.field-meta.xml
<CustomField>
    <fullName>DME_Diagnosis_Dependent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DME Diagnosis Dependent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/E0218__c.field-meta.xml
<CustomField>
    <fullName>E0218__c</fullName>
    <label>E0218</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <externalId>true</externalId>
    <label>Group Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_Is_Policy_Funded__c.field-meta.xml
<CustomField>
    <fullName>How_Is_Policy_Funded__c</fullName>
    <label>How Is Policy Funded</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Fully</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Acupuncture_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Acupuncture_Authorization__c</fullName>
    <label>How to Obtain Acupuncture Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Chiro_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Chiro_Authorization__c</fullName>
    <label>How to Obtain Chiro Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_To_Obtain_DME_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_To_Obtain_DME_Authorization__c</fullName>
    <label>How To Obtain DME Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Injection_Authorization_Process__c.field-meta.xml
<CustomField>
    <fullName>Injection_Authorization_Process__c</fullName>
    <label>Injection Authorization Process</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7320__c.field-meta.xml
<CustomField>
    <fullName>J7320__c</fullName>
    <label>J7320</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7322__c.field-meta.xml
<CustomField>
    <fullName>J7322__c</fullName>
    <label>J7322</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7322_Diagnosis_Driven__c.field-meta.xml
<CustomField>
    <fullName>J7322_Diagnosis_Driven__c</fullName>
    <label>J7322 Diagnosis Driven</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7324__c.field-meta.xml
<CustomField>
    <fullName>J7324__c</fullName>
    <label>J7324</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7325__c.field-meta.xml
<CustomField>
    <fullName>J7325__c</fullName>
    <label>J7325</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Secondary_Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Plan_Effective_Date__c</fullName>
    <label>Secondary Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Start_of_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_of_Plan_Year__c</fullName>
    <label>Start of Plan Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster__c</fullName>
    <label>WC Adjuster</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster_Fax__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster_Fax__c</fullName>
    <label>WC Adjuster Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster_Phone__c</fullName>
    <label>WC Adjuster Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Fax__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Fax__c</fullName>
    <label>WC Authorization Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Phone__c</fullName>
    <label>WC Authorization Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Required_for_Visits_NEW__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Required_for_Visits_NEW__c</fullName>
    <label>WC Authorization Required for Visits</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Injury_State__c.field-meta.xml
<CustomField>
    <fullName>WC_Injury_State__c</fullName>
    <label>Injury State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company__c</fullName>
    <label>Insurance Company</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_City__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_City__c</fullName>
    <label>Insurance Company City</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Phone__c</fullName>
    <label>Insurance Company Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_State__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_State__c</fullName>
    <label>Insurance Company State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Street__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Street__c</fullName>
    <label>Insurance Company Street</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Zip__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Zip__c</fullName>
    <label>Insurance Company Zip</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WCB_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>WCB_Case_Number__c</fullName>
    <label>WCB Case Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Where_To_Submit_MG2_C4_Form__c.field-meta.xml
<CustomField>
    <fullName>Where_To_Submit_MG2_C4_Form__c</fullName>
    <label>Where To Submit MG2 C4 Form</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkerCompVerificationFormControllerTest.cls
@IsTest
public class WorkerCompVerificationFormControllerTest {
     @TestSetup
    public static void dataSetup(){
        Account acc = new Account(Name ='Test');
        insert acc;
       
        Case cs = new Case();
        cs.Status = 'New';
        cs.Patient_Name__c = 'Test Patient';
        cs.Patient_Date_of_Birth__c = System.today();
       // cs.Intake__c = opp.Id;
        cs.Subject = 'test subject';
        cs.PIP_Date_of_Loss__c = System.today();
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Authorization_Required_for_Acupuncture__c = true;
        ins.Authorization_Required_for_DME__c = true;
        ins.Authorization_Required_for_OT__c = true;
        ins.Authorization_Required_for_Procedures__c = true;
        ins.Authorization_Required_for_PT__c = true;
       
        ins.Patient_Date_Of_Birth__c = System.today();
        ins.Call_Reference_Number__c = '';
        ins.Can_Out_Of_Network_Provider_Treat_Here__c = '';
        ins.Can_we_buy_and_bill_injection_codes__c = '';
        ins.Claim_Number__c = '';
        ins.Claims_Address__c = '';
        ins.Conservative_Modalities_Combined_Per_Day__c = true;
        ins.Count_As_1_Or_2_Visits__c = '';
        ins.DME_Benefits_Notes__c = 'DME Benefits Notes';
        ins.DME_Diagnosis_Codes__c = '';
        ins.DME_Diagnosis_Dependent__c = true;
        ins.E0218__c = '';
        ins.Group_Number__c = '';
        ins.How_Is_Policy_Funded__c = '';
        ins.How_to_Obtain_Chiro_Authorization__c = '';
        ins.How_To_Obtain_DME_Authorization__c = '';
        ins.Injection_Authorization_Process__c = 'Injection Authorization Process';
        ins.J7320__c = 'Yes covered, NO AUTH REQ';
        ins.J7322__c = 'Yes covered, NO AUTH REQ';
        ins.J7322_Diagnosis_Driven__c = 'Yes';
        ins.J7324__c = 'Yes covered, NO AUTH REQ';
        ins.J7325__c = 'Yes covered, NO AUTH REQ';
        ins.VOB_Case__c = cs.Id;
        ins.Plan_Effective_Date__c = System.today();
        ins.Start_of_Plan_Year__c = System.today();
        ins.Secondary_Plan_Effective_Date__c = System.today();
        ins.Date_of_Accident__c = System.today();
        insert ins;
        
        
    }   
     @IsTest
    static void testWorkerCompVerificationFormController() {
        
        Test.startTest();
        List<Insurance_Plan__c> plans = [
            SELECT
             Id,
             Patient_Name__c,
             WC_Injury_State__c,
             Patient_Date_Of_Birth__c,
             Date_of_Accident__c,
             WC_Insurance_Company__c,
             WC_Insurance_Company_Phone__c,
             WC_Insurance_Company_Street__c,
             WC_Insurance_Company_City__c,
             WC_Insurance_Company_State__c,
             WC_Insurance_Company_Zip__c,
             WCB_Case_Number__c,
             Claim_Number__c,
             WC_Adjuster__c,
             WC_Adjuster_Phone__c,
             WC_Adjuster_Fax__c,
             Where_To_Submit_MG2_C4_Form__c,
             WC_Authorization_Phone__c,
             WC_Authorization_Fax__c,
             WC_Authorization_Required_for_Visits_NEW__c,
             WC_Approved_Body_Region__c,
             Employer__c,
             Employer_Phone__c,
             WC_PT_Covered_NEW__c,
             Chiropractor_Covered_by_WC_NEW__c,
             Acupuncture_Covered_by_WC_NEW__c,
             Are_We_In_Network_Out_Network_Provider__c, 
             Can_Out_Of_Network_Provider_Treat_Here__c,
             If_NY_Is_Patient_Address_Listed_In_NY__c,
             Workers_Comp_Attorney__c,
             Workers_Comp_Attorney_Fax__c,
             Workers_Comp_Attorney_Phone__c,
             WC_Conservative_Care_on_Same_Day__c
             FROM Insurance_Plan__c order by createddate DESC LIMIT 1 ];
        
        List<Case> caseLst = [Select Id, 
                               Owner.Name,
                               ClosedDate
                               FROM Case ];
       
        
        PageReference vfPage = Page.WorkerCompVerificationFormPDF;
        Test.setCurrentPage(vfPage);
        ApexPages.currentPage().getParameters().put('id',caseLst[0].Id);
        WorkerCompVerificationFormController insp = new WorkerCompVerificationFormController();
        
        Test.stopTest();
    }

}