force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Length__c.field-meta.xml
<CustomField>
    <fullName>Call_Length__c</fullName>
    <label>Call Length</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_Out_Of_Network_Provider_Treat_Here__c.field-meta.xml
<CustomField>
    <fullName>Can_Out_Of_Network_Provider_Treat_Here__c</fullName>
    <label>Can Out Of Network Provider Treat Here</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_patient_treat_at_ASC__c.field-meta.xml
<CustomField>
    <fullName>Can_patient_treat_at_ASC__c</fullName>
    <label>Can Patient Treat at ASC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_we_buy_and_bill_injection_codes__c.field-meta.xml
<CustomField>
    <fullName>Can_we_buy_and_bill_injection_codes__c</fullName>
    <label>Can we buy and bill injection codes?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_Combined__c</fullName>
    <label>Chiro Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claims_Address__c.field-meta.xml
<CustomField>
    <fullName>Claims_Address__c</fullName>
    <label>Claims Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Date_of_Accident__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Accident__c</fullName>
    <label>Date of Accident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <label>Employer</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Acupuncture_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Acupuncture_Authorization__c</fullName>
    <label>How to Obtain Acupuncture Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Insurance_Company_Representative__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Representative__c</fullName>
    <label>Insurance Company Representative</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Annual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Annual_Deductible__c</fullName>
    <label>Medicare Annual Deductible</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Deductible_Met__c</fullName>
    <label>Medicare Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Member_Id__c</fullName>
    <label>Medicare Member Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_OT_Benefits_Used_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Medicare_OT_Benefits_Used_To_Date__c</fullName>
    <label>Medicare OT Benefits Used To Date</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_PT_Benefits_Used_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Medicare_PT_Benefits_Used_To_Date__c</fullName>
    <label>Medicare PT Benefits Used To Date</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Replacement_Plan_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Replacement_Plan_Carrier__c</fullName>
    <label>Medicare Replacement Plan Carrier</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/OT_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>OT_Visits_Combined__c</fullName>
    <label>OT Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PPO</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>HMO</fullName>
            </value>
            <value>
                <fullName>EPO</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Procedure_Benefits_Notes__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Benefits_Notes__c</fullName>
    <label>Procedure Benefits Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Secondary_Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Plan_Effective_Date__c</fullName>
    <label>Secondary Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Start_of_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_of_Plan_Year__c</fullName>
    <label>Start of Plan Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Follows_Medicare_Guidelines__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Follows_Medicare_Guidelines__c</fullName>
    <label>Supplemental Follows Medicare Guidelines</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Plan_Type__c</fullName>
    <label>Supplemental Plan Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Policy_On_File_NEW__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Policy_On_File_NEW__c</fullName>
    <label>Supplemental Policy On File</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MedicareVerifyFormControllerTest.cls
@IsTest
public class MedicareVerifyFormControllerTest {
    @TestSetup
    public static void dataSetup(){
        Account acc = new Account(Name ='Test');
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate= Date.today();
        opp.StageName= 'Initial Appointment';
        opp.Mid_Back_Pain__c = true;
        opp.Neck_Pain__c = true;
        opp.Lower_Back_Pain_Sciatica__c = true;
        opp.Leg_Pain__c = true;
        opp.Knee_Pain__c = true;
        opp.Hip_Pain__c = true;
        opp.Foot_Ankle_Pain__c = true;
        opp.Shoulder_Pain__c = true;
        opp.Elbow_Pain__c = true;
        opp.Wrist_Hand_Pain__c = true;
        opp.Scoliosis__c = true;
        opp.Headache_Migraine__c = true;
        opp.Vertigo__c = true;
        opp.Neurological_Condition__c = true;
        opp.Wellness_No_Pain__c = true;
        opp.Other_Condition__c = true;
        opp.LeadSource = 'Internet_Google';
        insert opp;
        
        Case cs = new Case();
        cs.Status = 'New';
        cs.Patient_Name__c = 'Test Patient';
        cs.Patient_Date_of_Birth__c = System.today();
        cs.Intake__c = opp.Id;
        cs.Subject = 'test subject';
        cs.PIP_Date_of_Loss__c = System.today();
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Patient_Date_of_Birth__c = System.today()-100;
        ins.Call_Length__c = '';
        ins.Supplemental_Policy_On_File_NEW__c = 'N/A';
        ins.Supplemental_Follows_Medicare_Guidelines__c = 'N/A';
        ins.Call_Reference_Number__c = '';
        ins.Can_Out_Of_Network_Provider_Treat_Here__c = '';
        ins.Can_we_buy_and_bill_injection_codes__c = '';
        ins.Claim_Number__c = '';
        ins.Claims_Address__c = '';
        ins.VOB_Case__c = cs.Id;
        ins.Plan_Effective_Date__c = System.today();
        ins.Start_of_Plan_Year__c = System.today();
        ins.Secondary_Plan_Effective_Date__c = System.today();
        ins.Date_of_Accident__c = System.today();
        insert ins;
        
        
    }
    
    
    @IsTest
    static void testMedicareVerifyFormController() {
        
        Test.startTest();
        List<Insurance_Plan__c> plans = [
            SELECT
            RecordType.Name,
            Patient_Name__c,
            Plan_Type__c,
            Claims_Address__c,
            Patient_Date_of_Birth__c,
            Medicare_Annual_Deductible__c,
            Medicare_Deductible_Met__c,
            Plan_Effective_Date__c,
            Medicare_PT_Benefits_Used_To_Date__c,
            Medicare_Replacement_Plan_Carrier__c,
            Medicare_OT_Benefits_Used_To_Date__c,
            Supplemental_Policy_On_File_NEW__c,
            Supplemental_Plan_Type__c,
            Supplemental_Follows_Medicare_Guidelines__c,
            Medicare_Member_Id__c,
            Insurance_Company_Representative__c,
            Call_Reference_Number__c,
            Call_Length__c,
            Procedure_Benefits_Notes__c,
            OT_Visits_Combined__c
            
            FROM Insurance_Plan__c LIMIT 1 ];
        
        List<Case> caseLst = [Select Id, 
                              Patient_VOB__r.Name,
                              Patient_Date_of_Birth__c,
                              Personal_Injury_Attorney__c,
                              PIP_LOP_on_File_NEW__c,
                              Declaration_Page_Received__c,
                              Police_Report_Received__c,
                              PIP_Most_Up_To_Date_PIP_Ledger__c,
                              PIP_Notes__c,
                              Employer__c
                              
                              FROM Case ];
        
        PageReference vfPage = Page.MedicareVerificationFormPdf;
        Test.setCurrentPage(vfPage);
        ApexPages.currentPage().getParameters().put('id',caseLst[0].Id);
        MedicareVerifyFormController insp = new MedicareVerifyFormController();
        
        Test.stopTest();
    }
}