force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Length__c.field-meta.xml
<CustomField>
    <fullName>Call_Length__c</fullName>
    <label>Call Length</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claims_Address__c.field-meta.xml
<CustomField>
    <fullName>Claims_Address__c</fullName>
    <label>Claims Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Insurance_Company_Representative__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Representative__c</fullName>
    <label>Insurance Company Representative</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Annual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Annual_Deductible__c</fullName>
    <label>Medicare Annual Deductible</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Deductible_Met__c</fullName>
    <label>Medicare Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Member_Id__c</fullName>
    <label>Medicare Member Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Notes__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Notes__c</fullName>
    <label>Medicare Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_OT_Benefits_Used_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Medicare_OT_Benefits_Used_To_Date__c</fullName>
    <label>Medicare OT Benefits Used To Date</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_PT_Benefits_Used_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Medicare_PT_Benefits_Used_To_Date__c</fullName>
    <label>Medicare PT Benefits Used To Date</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medicare_Replacement_Plan_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Replacement_Plan_Carrier__c</fullName>
    <label>Medicare Replacement Plan Carrier</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/OT_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>OT_Visits_Combined__c</fullName>
    <label>OT Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PPO</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>HMO</fullName>
            </value>
            <value>
                <fullName>EPO</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Procedure_Benefits_Notes__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Benefits_Notes__c</fullName>
    <label>Procedure Benefits Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Follows_Medicare_Guidelines__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Follows_Medicare_Guidelines__c</fullName>
    <label>Supplemental Follows Medicare Guidelines</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Plan_Type__c</fullName>
    <label>Supplemental Plan Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Supplemental_Policy_On_File_NEW__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Policy_On_File_NEW__c</fullName>
    <label>Supplemental Policy On File</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/recordTypes/Medicare.recordType-meta.xml
<RecordType>
    <fullName>Medicare</fullName>
    <active>true</active>
    <label>Medicare</label>
</RecordType>

force-app/main/default/objects/Insurance_Verification__c/Insurance_Verification__c.object-meta.xml
<CustomObject>
    <label>Insurance/Claim Information</label>
    <nameField>
        <displayFormat>IV-{000000000}</displayFormat>
        <label>Insurance/Claim Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance/Claim Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Verification__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <formula>IF( NOT( ISBLANK(Potential_Patient__r.Lead_Date_of_Birth__c) ) ,Potential_Patient__r.Lead_Date_of_Birth__c, Patient__r.Date_of_Birth__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/fields/OT_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>OT_Visits_Combined__c</fullName>
    <label>OT Visits Combined?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/fields/Primary_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Primary_Insurance__c</fullName>
    <label>Primary Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Health_Insurance_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/fields/Secondary_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Insurance__c</fullName>
    <label>Secondary Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Health_Insurance_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/MedicareVerifyFormController.cls
public class MedicareVerifyFormController {
    public Case caseRecord{get;set;}
    public Insurance_Plan__c insurancePlanRecord { get; private set; }
    //public Insurance_Verification__c ic { get; private set; }
   
    public String patientName{get;set;}
    public String patientDOB{get;set;}
    public String effectiveDate{get;set;}
    public String primaryeffectiveDate{get;set;}
 
    public Boolean isMedicareRecordType{get;set;}
    public String isCheckType {get;set;}
    public String todayDate {
        get {
            return Datetime.now().format('MM/dd/yyyy', 'EST');
        }
        set;
    } 
    
     public MedicareVerifyFormController() {
        this.insurancePlanRecord = new Insurance_Plan__c();
        
        String csId = ApexPages.currentPage().getParameters().get('id');
        
        caseRecord = [Select Id, 
                      PIP_Primary_NEW__c,
                      PIP_Accident_State__c,
                      Primary_Insurance__c,
                      Secondary_Insurance__c,
                       Patient_VOB__c,
                      Patient_VOB__r.Name,
                      Patient_VOB__r.Date_of_Birth__c,
                      Patient_Name__c,
                      Patient_Date_of_Birth__c,
                      Member_ID__c,
                           Intake__r.Appointment__r.Location_Name__c
                      //,Intake__r.Appointment__r.Intake_Completed_By__c
                      FROM Case where Id=:csId];
        if(caseRecord.Patient_Name__c != null) {
            patientName = caseRecord.Patient_Name__c;
        } else if(caseRecord.Patient_VOB__r.Name != null) {
            patientName = caseRecord.Patient_VOB__r.Name;
        } 
        
       /* if(caseRecord.Patient_Date_of_Birth__c != null) {
            patientDOB = caseRecord.Patient_Date_of_Birth__c.format();
        } else if(caseRecord.Patient_VOB__r.Date_of_Birth__c != null) {
            patientDOB = caseRecord.Patient_VOB__r.Date_of_Birth__c.format();
        }*/
        
        System.debug('::: Patient name and dob - '+patientName+' and '+patientDOB);
        List<Insurance_Plan__c> plans = [
            SELECT
            RecordType.Name,
            Patient_Name__c,
            Plan_Type__c,
            Claims_Address__c,
            Patient_Date_of_Birth__c,
            Medicare_Annual_Deductible__c,
            Medicare_Deductible_Met__c,
            Plan_Effective_Date__c,
            Medicare_PT_Benefits_Used_To_Date__c,
            Medicare_Replacement_Plan_Carrier__c,
            Medicare_OT_Benefits_Used_To_Date__c,
            Supplemental_Policy_On_File_NEW__c,
            Supplemental_Plan_Type__c,
            Supplemental_Follows_Medicare_Guidelines__c,
            Medicare_Member_Id__c,
           Insurance_Company_Representative__c,
            Call_Reference_Number__c,
            Call_Length__c,
            Procedure_Benefits_Notes__c,
            OT_Visits_Combined__c,
            Medicare_Notes__c 
            
            FROM
            Insurance_Plan__c
            WHERE
            VOB_Case__c = :csId
             order by createddate DESC
            LIMIT 1
        ];
        
        if (plans != null && plans.size() > 0) {
            system.debug(plans);
            this.insurancePlanRecord = plans[0];
            
        }
        
        if(insurancePlanRecord.Plan_Effective_Date__c!= null) {
            effectiveDate = insurancePlanRecord.Plan_Effective_Date__c.format();
        }
        if(insurancePlanRecord.Plan_Effective_Date__c!= null) {
            primaryeffectiveDate = insurancePlanRecord.Plan_Effective_Date__c.format();
        }
          if(insurancePlanRecord.Patient_Date_of_Birth__c != null) {
            patientDOB = insurancePlanRecord.Patient_Date_of_Birth__c.format();
          }
        if(insurancePlanRecord.RecordType.Name != null) {
            isMedicareRecordType = (insurancePlanRecord.RecordType.Name == 'Medicare') ? true : false;
            isCheckType = (isMedicareRecordType == true) ? 'Yes' : 'No';
        }
         if(insurancePlanRecord.Supplemental_Policy_On_File_NEW__c == 'N/A') {
             insurancePlanRecord.Supplemental_Policy_On_File_NEW__c = '';
             
         }
          if(insurancePlanRecord.Supplemental_Follows_Medicare_Guidelines__c == 'N/A') {
             insurancePlanRecord.Supplemental_Follows_Medicare_Guidelines__c = '';
             
         }
       
        
     }

}