force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Acupuncture__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Acupuncture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Acupuncture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_DME__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_DME__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for DME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_OT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for OT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Procedures__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Procedures</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_PT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_PT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for PT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Billable_Time_Limit_For_A4556__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Limit_For_A4556__c</fullName>
    <label>Billable Time Limit For A4556</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Billable_Time_Limit_For_A4557__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Limit_For_A4557__c</fullName>
    <label>Billable Time Limit For A4557</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Billable_Time_Limit_For_E0218__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Limit_For_E0218__c</fullName>
    <label>Billable Time Limit For E0218</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Billable_Time_Limit_For_E0748__c.field-meta.xml
<CustomField>
    <fullName>Billable_Time_Limit_For_E0748__c</fullName>
    <label>Billable Time Limit For E0748</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Length__c.field-meta.xml
<CustomField>
    <fullName>Call_Length__c</fullName>
    <label>Call Length</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_Out_Of_Network_Provider_Treat_Here__c.field-meta.xml
<CustomField>
    <fullName>Can_Out_Of_Network_Provider_Treat_Here__c</fullName>
    <label>Can Out Of Network Provider Treat Here</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_patient_treat_at_ASC__c.field-meta.xml
<CustomField>
    <fullName>Can_patient_treat_at_ASC__c</fullName>
    <label>Can Patient Treat at ASC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_we_buy_and_bill_injection_codes__c.field-meta.xml
<CustomField>
    <fullName>Can_we_buy_and_bill_injection_codes__c</fullName>
    <label>Can we buy and bill injection codes?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_Combined__c</fullName>
    <label>Chiro Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claims_Address__c.field-meta.xml
<CustomField>
    <fullName>Claims_Address__c</fullName>
    <label>Claims Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Conservative_Modalities_Combined_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Conservative_Modalities_Combined_Per_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conservative Modalities Combined Per Day</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Count_As_1_Or_2_Visits__c.field-meta.xml
<CustomField>
    <fullName>Count_As_1_Or_2_Visits__c</fullName>
    <label>Count As 1 Or 2 Visits</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Benefits_Notes__c.field-meta.xml
<CustomField>
    <fullName>DME_Benefits_Notes__c</fullName>
    <label>DME Benefits Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Diagnosis_Codes__c.field-meta.xml
<CustomField>
    <fullName>DME_Diagnosis_Codes__c</fullName>
    <label>DME Diagnosis Codes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/DME_Diagnosis_Dependent__c.field-meta.xml
<CustomField>
    <fullName>DME_Diagnosis_Dependent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DME Diagnosis Dependent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/E0218__c.field-meta.xml
<CustomField>
    <fullName>E0218__c</fullName>
    <label>E0218</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <externalId>true</externalId>
    <label>Group Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_Is_Policy_Funded__c.field-meta.xml
<CustomField>
    <fullName>How_Is_Policy_Funded__c</fullName>
    <label>How Is Policy Funded</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Fully</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Acupuncture_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Acupuncture_Authorization__c</fullName>
    <label>How to Obtain Acupuncture Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Chiro_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Chiro_Authorization__c</fullName>
    <label>How to Obtain Chiro Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_To_Obtain_DME_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_To_Obtain_DME_Authorization__c</fullName>
    <label>How To Obtain DME Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Injection_Authorization_Process__c.field-meta.xml
<CustomField>
    <fullName>Injection_Authorization_Process__c</fullName>
    <label>Injection Authorization Process</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7320__c.field-meta.xml
<CustomField>
    <fullName>J7320__c</fullName>
    <label>J7320</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7322__c.field-meta.xml
<CustomField>
    <fullName>J7322__c</fullName>
    <label>J7322</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7322_Diagnosis_Driven__c.field-meta.xml
<CustomField>
    <fullName>J7322_Diagnosis_Driven__c</fullName>
    <label>J7322 Diagnosis Driven</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7324__c.field-meta.xml
<CustomField>
    <fullName>J7324__c</fullName>
    <label>J7324</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/J7325__c.field-meta.xml
<CustomField>
    <fullName>J7325__c</fullName>
    <label>J7325</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsurancePlanDocFlowControllerTest.cls
@isTest
public class InsurancePlanDocFlowControllerTest {
    @isTest static void testInsurancePlanDocs() {
        Account acc = new Account(Name ='Test');
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate= Date.today();
        opp.StageName= 'Initial Appointment';
        opp.Mid_Back_Pain__c = true;
        opp.Neck_Pain__c = true;
        opp.Lower_Back_Pain_Sciatica__c = true;
        opp.Leg_Pain__c = true;
        opp.Knee_Pain__c = true;
        opp.Hip_Pain__c = true;
        opp.Foot_Ankle_Pain__c = true;
        opp.Shoulder_Pain__c = true;
        opp.Elbow_Pain__c = true;
        opp.Wrist_Hand_Pain__c = true;
        opp.Scoliosis__c = true;
        opp.Headache_Migraine__c = true;
        opp.Vertigo__c = true;
        opp.Neurological_Condition__c = true;
        opp.Wellness_No_Pain__c = true;
        opp.Other_Condition__c = true;
        opp.LeadSource = 'Internet_Google';
        opp.AccountId = acc.Id;
        insert opp;
        
        Case cs = new Case();
        cs.Status = 'New';
        cs.Intake__c = opp.Id;
        cs.Patient_VOB__c = acc.Id;
        cs.Subject = 'test subject';
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.VOB_Case__c = cs.Id;
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Authorization_Required_for_Acupuncture__c = true;
        ins.Authorization_Required_for_DME__c = true;
        ins.Authorization_Required_for_OT__c = true;
        ins.Authorization_Required_for_Procedures__c = true;
        ins.Authorization_Required_for_PT__c = true;
        ins.Billable_Time_Limit_For_A4556__c = 'Billable time';
        ins.Billable_Time_Limit_For_A4557__c = '';
        ins.Billable_Time_Limit_For_E0218__c = '';
        ins.Billable_Time_Limit_For_E0748__c = '';
        ins.Call_Length__c = '';
        ins.Call_Reference_Number__c = '';
        ins.Can_Out_Of_Network_Provider_Treat_Here__c = '';
        ins.Can_we_buy_and_bill_injection_codes__c = '';
        ins.Claim_Number__c = '';
        ins.Claims_Address__c = '';
        ins.Conservative_Modalities_Combined_Per_Day__c = true;
        ins.Count_As_1_Or_2_Visits__c = '';
        ins.DME_Benefits_Notes__c = 'DME Benefits Notes';
        ins.DME_Diagnosis_Codes__c = '';
        ins.DME_Diagnosis_Dependent__c = true;
        ins.E0218__c = '';
        ins.Group_Number__c = '';
        ins.How_Is_Policy_Funded__c = '';
        ins.How_to_Obtain_Chiro_Authorization__c = '';
        ins.How_To_Obtain_DME_Authorization__c = '';
        ins.Injection_Authorization_Process__c = 'Injection Authorization Process';
        ins.J7320__c = 'Yes covered, NO AUTH REQ';
        ins.J7322__c = 'Yes covered, NO AUTH REQ';
        ins.J7322_Diagnosis_Driven__c = 'Yes';
        ins.J7324__c = 'Yes covered, NO AUTH REQ';
        ins.J7325__c = 'Yes covered, NO AUTH REQ';
        
        insert ins;
        
        List<Id> caseIds = new List<Id>();
        Test.startTest();
        caseIds.add(cs.Id);
        InsurancePlanDocFlowController.generateAndSendPDFDocument(caseIds);
        Test.stopTest();
    }
    
    @isTest static void testInsurancePlanDocs2() {
        Account acc = new Account(Name ='Test');
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.CloseDate= Date.today();
        opp.StageName= 'Initial Appointment';
        opp.Mid_Back_Pain__c = true;
        opp.Neck_Pain__c = true;
        opp.Lower_Back_Pain_Sciatica__c = true;
        opp.Leg_Pain__c = true;
        opp.Knee_Pain__c = true;
        opp.Hip_Pain__c = true;
        opp.Foot_Ankle_Pain__c = true;
        opp.Shoulder_Pain__c = true;
        opp.Elbow_Pain__c = true;
        opp.Wrist_Hand_Pain__c = true;
        opp.Scoliosis__c = true;
        opp.Headache_Migraine__c = true;
        opp.Vertigo__c = true;
        opp.Neurological_Condition__c = true;
        opp.Wellness_No_Pain__c = true;
        opp.Other_Condition__c = true;
        opp.LeadSource = 'Internet_Google';
        opp.AccountId = acc.Id;
        insert opp;
        
        Case cs = new Case();
        cs.Status = 'New';
        cs.Intake__c = opp.Id;
        cs.Subject = 'test subject';
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.VOB_Case__c = cs.Id;
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Authorization_Required_for_Acupuncture__c = true;
        ins.Authorization_Required_for_DME__c = true;
        ins.Authorization_Required_for_OT__c = true;
        ins.Authorization_Required_for_Procedures__c = true;
        ins.Authorization_Required_for_PT__c = true;
        ins.Billable_Time_Limit_For_A4556__c = 'Billable time';
        ins.Billable_Time_Limit_For_A4557__c = '';
        ins.Billable_Time_Limit_For_E0218__c = '';
        ins.Billable_Time_Limit_For_E0748__c = '';
        ins.Call_Length__c = '';
        ins.Call_Reference_Number__c = '';
        ins.Can_Out_Of_Network_Provider_Treat_Here__c = '';
        ins.Can_we_buy_and_bill_injection_codes__c = '';
        ins.Claim_Number__c = '';
        ins.Claims_Address__c = '';
        ins.Conservative_Modalities_Combined_Per_Day__c = true;
        ins.Count_As_1_Or_2_Visits__c = '';
        ins.DME_Benefits_Notes__c = 'DME Benefits Notes';
        ins.DME_Diagnosis_Codes__c = '';
        ins.DME_Diagnosis_Dependent__c = true;
        ins.E0218__c = '';
        ins.Group_Number__c = '';
        ins.How_Is_Policy_Funded__c = '';
        ins.How_to_Obtain_Chiro_Authorization__c = '';
        ins.How_To_Obtain_DME_Authorization__c = '';
        ins.Injection_Authorization_Process__c = 'Injection Authorization Process';
        ins.J7320__c = 'Yes covered, NO AUTH REQ';
        ins.J7322__c = 'Yes covered, NO AUTH REQ';
        ins.J7322_Diagnosis_Driven__c = 'Yes';
        ins.J7324__c = 'Yes covered, NO AUTH REQ';
        ins.J7325__c = 'Yes covered, NO AUTH REQ';
        
        insert ins;
        
        List<Id> caseIds = new List<Id>();
        Test.startTest();
        caseIds.add(cs.Id);
        InsurancePlanDocFlowController.generateAndSendPDFDocument(caseIds);
        Test.stopTest();
    }
}