force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Acupuncture_Covered_by_WC_NEW__c.field-meta.xml
<CustomField>
    <fullName>Acupuncture_Covered_by_WC_NEW__c</fullName>
    <label>Acupuncture Covered by WC</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Are_We_In_Network_Out_Network_Provider__c.field-meta.xml
<CustomField>
    <fullName>Are_We_In_Network_Out_Network_Provider__c</fullName>
    <label>Are We In-Network/Out Network Provider?</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_Out_Of_Network_Provider_Treat_Here__c.field-meta.xml
<CustomField>
    <fullName>Can_Out_Of_Network_Provider_Treat_Here__c</fullName>
    <label>Can Out Of Network Provider Treat Here</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiropractor_Covered_by_WC_NEW__c.field-meta.xml
<CustomField>
    <fullName>Chiropractor_Covered_by_WC_NEW__c</fullName>
    <label>Chiropractor Covered by WC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Date_of_Accident__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Accident__c</fullName>
    <label>Date of Accident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <label>Employer</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/If_NY_Is_Patient_Address_Listed_In_NY__c.field-meta.xml
<CustomField>
    <fullName>If_NY_Is_Patient_Address_Listed_In_NY__c</fullName>
    <label>If NY, Is Patient Address Listed In NY?</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster__c</fullName>
    <label>WC Adjuster</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster_Fax__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster_Fax__c</fullName>
    <label>WC Adjuster Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Adjuster_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Adjuster_Phone__c</fullName>
    <label>WC Adjuster Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Approved_Body_Region__c.field-meta.xml
<CustomField>
    <fullName>WC_Approved_Body_Region__c</fullName>
    <label>Approved Body Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Fax__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Fax__c</fullName>
    <label>WC Authorization Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Phone__c</fullName>
    <label>WC Authorization Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Authorization_Required_for_Visits_NEW__c.field-meta.xml
<CustomField>
    <fullName>WC_Authorization_Required_for_Visits_NEW__c</fullName>
    <label>WC Authorization Required for Visits</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Conservative_Care_on_Same_Day__c.field-meta.xml
<CustomField>
    <fullName>WC_Conservative_Care_on_Same_Day__c</fullName>
    <label>WC Conservative Care on Same Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
                <isActive>false</isActive>
                <label>Bundled</label>
            </value>
            <value>
                <fullName>Paid Individually</fullName>
                <isActive>false</isActive>
                <label>Paid Individually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Injury_State__c.field-meta.xml
<CustomField>
    <fullName>WC_Injury_State__c</fullName>
    <label>Injury State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company__c</fullName>
    <label>Insurance Company</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_City__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_City__c</fullName>
    <label>Insurance Company City</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Phone__c</fullName>
    <label>Insurance Company Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_State__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_State__c</fullName>
    <label>Insurance Company State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Street__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Street__c</fullName>
    <label>Insurance Company Street</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_Insurance_Company_Zip__c.field-meta.xml
<CustomField>
    <fullName>WC_Insurance_Company_Zip__c</fullName>
    <label>Insurance Company Zip</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WC_PT_Covered_NEW__c.field-meta.xml
<CustomField>
    <fullName>WC_PT_Covered_NEW__c</fullName>
    <label>PT Covered?</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/WCB_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>WCB_Case_Number__c</fullName>
    <label>WCB Case Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Where_To_Submit_MG2_C4_Form__c.field-meta.xml
<CustomField>
    <fullName>Where_To_Submit_MG2_C4_Form__c</fullName>
    <label>Where To Submit MG2 C4 Form</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Workers_Comp_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Workers_Comp_Attorney__c</fullName>
    <label>Workers Comp Attorney</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Workers_Comp_Attorney_Fax__c.field-meta.xml
<CustomField>
    <fullName>Workers_Comp_Attorney_Fax__c</fullName>
    <label>Workers Comp Attorney Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Workers_Comp_Attorney_Phone__c.field-meta.xml
<CustomField>
    <fullName>Workers_Comp_Attorney_Phone__c</fullName>
    <label>Workers Comp Attorney Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/WorkerCompVerificationFormController.cls
public class WorkerCompVerificationFormController {
     public Case caseRecord{get;set;}
     public Insurance_Plan__c insurancePlanRecord { get; private set; }
     public String patientDOB{get;set;}
     public String closedate{get;set;}
     public String dateOfAccident{get;set;}
     public WorkerCompVerificationFormController() {
        this.insurancePlanRecord = new Insurance_Plan__c();
        
        String csId = ApexPages.currentPage().getParameters().get('id');
        
        caseRecord = [Select Id, 
                      //OwnerId,
                      Owner.Name,
                     // Owner.Username,
                      ClosedDate
                      FROM Case where Id=:csId];
         /*if (caseRecord.ClosedDate!= null ) {
             closedate = caseRecord.ClosedDate.format();
             System.debug(closedate);
         }*/
         closedate = Date.today().format();
          
        List<Insurance_Plan__c> plans = [
             SELECT
             Id,
             Patient_Name__c,
             WC_Injury_State__c,
             Patient_Date_Of_Birth__c,
             Date_of_Accident__c,
             WC_Insurance_Company__c,
             WC_Insurance_Company_Phone__c,
             WC_Insurance_Company_Street__c,
             WC_Insurance_Company_City__c,
             WC_Insurance_Company_State__c,
             WC_Insurance_Company_Zip__c,
             WCB_Case_Number__c,
             Claim_Number__c,
             WC_Adjuster__c,
             WC_Adjuster_Phone__c,
             WC_Adjuster_Fax__c,
             Where_To_Submit_MG2_C4_Form__c,
             WC_Authorization_Phone__c,
             WC_Authorization_Fax__c,
             WC_Authorization_Required_for_Visits_NEW__c,
             WC_Approved_Body_Region__c,
             Employer__c,
             WC_PT_Covered_NEW__c,
             Chiropractor_Covered_by_WC_NEW__c,
             Acupuncture_Covered_by_WC_NEW__c,
             Are_We_In_Network_Out_Network_Provider__c, 
             Can_Out_Of_Network_Provider_Treat_Here__c,
             If_NY_Is_Patient_Address_Listed_In_NY__c,
             Workers_Comp_Attorney__c,
             Workers_Comp_Attorney_Fax__c,
             Workers_Comp_Attorney_Phone__c,
             WC_Conservative_Care_on_Same_Day__c
             
             FROM Insurance_Plan__c WHERE
             VOB_Case__c = :csId
             order by createddate DESC
             LIMIT 1 ];
         
         if (plans != null && plans.size() > 0) {
             system.debug(plans);
             this.insurancePlanRecord = plans[0];
             
             if(insurancePlanRecord.Patient_Date_Of_Birth__c!= null) {
                 patientDOB = insurancePlanRecord.Patient_Date_Of_Birth__c.format();
                 System.debug(patientDOB);
             }
             if(insurancePlanRecord.Date_of_Accident__c!= null) {
                 dateOfAccident = insurancePlanRecord.Date_of_Accident__c.format();
             }
   
         }
     }
}