force-app/main/default/objects/CareCloud_Information__c/CareCloud_Information__c.object-meta.xml
<CustomObject>
    <description>CareCloud Providers and Locations</description>
    <label>CareCloud Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CareCloud Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CareCloud_Information__c/fields/CareCloud_Id__c.field-meta.xml
<CustomField>
    <fullName>CareCloud_Id__c</fullName>
    <externalId>true</externalId>
    <label>CareCloud Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acupuncturist</fullName>
            </value>
            <value>
                <fullName>Chiropractor</fullName>
            </value>
            <value>
                <fullName>Durable Medical Equipment &amp; Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle Surgery</fullName>
            </value>
            <value>
                <fullName>Multi-Specialty</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Occupational Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgery</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgeryofthe Spine</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Physical Therapist</fullName>
            </value>
            <value>
                <fullName>Physical Therapy</fullName>
            </value>
            <value>
                <fullName>Physical Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/CareCloud_Information__c/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

force-app/main/default/classes/CareCloudProvidersAndLocationsHelper.cls
public class CareCloudProvidersAndLocationsHelper implements Queueable, Database.AllowsCallouts {
    Private Static String BASE_ENDPOINT = 'https://api.carecloud.com/v2';
    Private boolean byPassBatch;
    
    public CareCloudProvidersAndLocationsHelper(Boolean byPassBatch){
        this.byPassBatch = byPassBatch;
    }
    
    public void execute(QueueableContext context) {       
        if(String.isNotBlank(CareCloudAPIHelper.accessToken)){
            List<CareCloud_Information__c> careCloudInfo = new List<CareCloud_Information__c>();
            
            for(CareCloudWrapperClasses.ProvidersWrapper_provider provider : fetchProviders()){
                careCloudInfo.add(new CareCloud_Information__c(
                	CareCloud_Id__c = 'P-'+provider.id,
                    Specialty__c = provider.speciality?.name,
                    Name = provider.name,
                    RecordTypeId =  Schema.SObjectType.CareCloud_Information__c.getRecordTypeInfosByName().get('Provider').getRecordTypeId()
                ));
            }
            
            for(CareCloudWrapperClasses.LocationsWrapper_location location : fetchLocations()){
                careCloudInfo.add(new CareCloud_Information__c(
                	CareCloud_Id__c = 'L-'+location.id,
                    Name = location.name,
                    RecordTypeId =  Schema.SObjectType.CareCloud_Information__c.getRecordTypeInfosByName().get('Location').getRecordTypeId()
                ));
            }
            
            for(CareCloudWrapperClasses.VisitReasonsWrapper visitreason : fetchVisitReasons()){
                careCloudInfo.add(new CareCloud_Information__c(
                	CareCloud_Id__c = 'VR-'+ visitreason.id,
                    Name = visitreason.name,
                    RecordTypeId =  Schema.SObjectType.CareCloud_Information__c.getRecordTypeInfosByName().get('Visit Reason').getRecordTypeId()
                ));
            }
            
            if(!careCloudInfo.isEmpty()){
                upsert careCloudInfo CareCloud_Id__c;
            }
        }
    }
    
    private List<CareCloudWrapperClasses.ProvidersWrapper_provider> fetchProviders(){
        HttpResponse resp = CalloutUtility.doCallout(BASE_ENDPOINT+'/providers', 'GET', new map<string,string>{'Authorization' => 'Bearer ' + CareCloudAPIHelper.accessToken}, '', 120000);
        CareCloudWrapperClasses.ProvidersWrapper providerResp = (CareCloudWrapperClasses.ProvidersWrapper) System.JSON.deserialize(resp.getBody(), CareCloudWrapperClasses.ProvidersWrapper.class);
        return providerResp.providers;
    }
    
    private List<CareCloudWrapperClasses.LocationsWrapper_location> fetchLocations(){
        HttpResponse resp = CalloutUtility.doCallout(BASE_ENDPOINT+'/locations?all_public=true', 'GET', new map<string,string>{'Authorization' => 'Bearer ' + CareCloudAPIHelper.accessToken}, '', 120000);
        CareCloudWrapperClasses.LocationsWrapper locationResp = (CareCloudWrapperClasses.LocationsWrapper) System.JSON.deserialize(resp.getBody(), CareCloudWrapperClasses.LocationsWrapper.class);
        return locationResp.locations;
    }
    
     private List<CareCloudWrapperClasses.VisitReasonsWrapper> fetchVisitReasons(){
        HttpResponse resp = CalloutUtility.doCallout(BASE_ENDPOINT+'/visit_reasons?request_types_only=false', 'GET', new map<string,string>{'Authorization' => 'Bearer ' + CareCloudAPIHelper.accessToken}, '', 120000);
        return (List<CareCloudWrapperClasses.VisitReasonsWrapper>) System.JSON.deserialize(resp.getBody(), List<CareCloudWrapperClasses.VisitReasonsWrapper>.class);
    }
}