force-app/main/default/objects/SPD__c/SPD__c.object-meta.xml
<CustomObject>
    <description>We created this object for new SPD workflow.</description>
    <label>SPD</label>
    <nameField>
        <displayFormat>SPD# {00000000}</displayFormat>
        <label>SPD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPD__c/fields/Current_Group_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Current_Group_Policy_Number__c</fullName>
    <label>Current Group Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPD__c/fields/SPD_Not_Applicable_to_GPN__c.field-meta.xml
<CustomField>
    <fullName>SPD_Not_Applicable_to_GPN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SPD Not Applicable to GPN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SPD_Creation_Exception_Rules__mdt/SPD_Creation_Exception_Rules__mdt.object-meta.xml
<CustomObject>
    <label>SPD Creation Exception Rule</label>
    <pluralLabel>SPD Creation Exception Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/SPD_Creation_Exception_Rules__mdt/fields/Excluded_GPNs__c.field-meta.xml
<CustomField>
    <fullName>Excluded_GPNs__c</fullName>
    <label>Excluded GPNs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/spdNotApplicableToGPNClass.cls
public class spdNotApplicableToGPNClass {
 @InvocableMethod(label='Update SPD Not Applicable to GPN Fields' description='To Update SPD Not Applicable to GPN Fields onDaily basis')
    public static void updateSpds(List<String> UpdatingGPN){
        
        SPD_Creation_Exception_Rules__mdt customMetadataRecords=[SELECT Id,MasterLabel,DeveloperName, Excluded_GPNs__c 
                FROM SPD_Creation_Exception_Rules__mdt 
                WHERE DeveloperName = :'SPD_Creation_Exceptions'
                LIMIT 1];
        List<String> excludedGPNsList = new List<String>();
            if (customMetadataRecords != null && String.isNotBlank(customMetadataRecords.Excluded_GPNs__c)) {
                excludedGPNsList = customMetadataRecords.Excluded_GPNs__c.split(',');
            }
        
                List<SPD__c> spdList=new List<SPD__c>();
                List<SPD__c> updatingSpdList=new List<SPD__c>();
                spdList=[SELECT id,SPD_Not_Applicable_to_GPN__c,Current_Group_Policy_Number__c 
                         FROM SPD__c WHERE Current_Group_Policy_Number__c IN:excludedGPNsList];
        for(SPD__c spd:spdList){
            spd.SPD_Not_Applicable_to_GPN__c=true;
            updatingSpdList.add(spd);
            
        }
        If(!updatingSpdList.isEmpty()){
            update updatingSpdList;
        }
            }
}