force-app/main/default/objects/dn_Denial__c/dn_Denial__c.object-meta.xml
<CustomObject>
    <label>Denial</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Denials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Denials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dn_Denial__c/fields/dn_Adjustment_Code_1__c.field-meta.xml
<CustomField>
    <fullName>dn_Adjustment_Code_1__c</fullName>
    <label>Adjustment Code 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dn_Denial__c/fields/dn_CO_100_Status__c.field-meta.xml
<CustomField>
    <fullName>dn_CO_100_Status__c</fullName>
    <label>CO-100 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>PAA</fullName>
            </value>
            <value>
                <fullName>SBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/dn_Denial__c/fields/dn_DENIED_CATEGORY_CODE__c.field-meta.xml
<CustomField>
    <fullName>dn_DENIED_CATEGORY_CODE__c</fullName>
    <label>Denied Category Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dn_Denial__c/fields/dn_DOS__c.field-meta.xml
<CustomField>
    <fullName>dn_DOS__c</fullName>
    <description>Date of Service</description>
    <label>DOS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/dn_Denial__c/fields/dn_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>dn_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Denials</relationshipLabel>
    <relationshipName>Denials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dn_Denial__c/fields/dn_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>dn_Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dnDenialBatch.cls
public class dnDenialBatch implements Database.Batchable<SObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Fetch CO-100 Underpaid records
        return Database.getQueryLocator([
            SELECT Id, dn_Patient_Account__r.dn_Name__c, dn_Provider_Id__c, dn_DOS__c
            FROM dn_Denial__c
            WHERE dn_Adjustment_Code_1__c = '100'
            AND dn_DENIED_CATEGORY_CODE__c = 'CO'
            AND dn_CO_100_Status__c = 'Underpaid'
        ]);
    }

    public void execute(Database.BatchableContext bc, List<dn_Denial__c> scope) {
        //dn_DenialHandler.processRecords(scope);
        system.debug('Stoped batch');
    }

    public void finish(Database.BatchableContext bc) {
        // Optional: send notification, debug log, etc.
    }
}