force-app/main/default/objects/AR_Accounts_Receivable__c/AR_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <label>Accounts Receivable</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Age_by_First_Billed__c.field-meta.xml
<CustomField>
    <fullName>AR_Age_by_First_Billed__c</fullName>
    <label>Age by First Billed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Age_by_Last_Billed__c.field-meta.xml
<CustomField>
    <fullName>AR_Age_by_Last_Billed__c</fullName>
    <label>Aging Bucket</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Balance__c.field-meta.xml
<CustomField>
    <fullName>AR_Balance__c</fullName>
    <label>Balance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Business_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Business_Entity_Id__c</fullName>
    <label>Business Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Debit_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Debit_Id__c</fullName>
    <externalId>true</externalId>
    <label>Debit Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Diagnosis1_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Diagnosis1_Code__c</fullName>
    <label>Diagnosis1 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_External_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>AR External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Insurance_Payments__c.field-meta.xml
<CustomField>
    <fullName>AR_Insurance_Payments__c</fullName>
    <label>Insurance Payments</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Insurance_Profile__c.field-meta.xml
<CustomField>
    <fullName>AR_Insurance_Profile__c</fullName>
    <label>Insurance Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Last_Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Last_Claim_Id__c</fullName>
    <label>Last Claim Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Location_Name__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>AR_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivables</relationshipLabel>
    <relationshipName>Accounts_Receivables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Payment_Variance__c.field-meta.xml
<CustomField>
    <fullName>AR_Payment_Variance__c</fullName>
    <formula>AR_Amount__c - VALUE(AR_Expected_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Policy_Type__c.field-meta.xml
<CustomField>
    <fullName>AR_Policy_Type__c</fullName>
    <label>Policy Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Priority_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Priority_Status__c</fullName>
    <label>Priority Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>F/U</fullName>
            </value>
            <value>
                <fullName>DND</fullName>
            </value>
            <value>
                <fullName>OLD</fullName>
            </value>
            <value>
                <fullName>mPMTDUE</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CRITICAL</fullName>
            </value>
            <value>
                <fullName>PATIENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Responsibility_Type__c.field-meta.xml
<CustomField>
    <fullName>AR_Responsibility_Type__c</fullName>
    <label>Responsibility Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Units__c.field-meta.xml
<CustomField>
    <fullName>AR_Units__c</fullName>
    <label>Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/AR_Value_Balance__c.field-meta.xml
<CustomField>
    <fullName>AR_Value_Balance__c</fullName>
    <label>Value Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Accounts_Receivable__c/fields/Injection_Status__c.field-meta.xml
<CustomField>
    <fullName>Injection_Status__c</fullName>
    <label>Injection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ST</fullName>
            </value>
            <value>
                <fullName>2ND</fullName>
            </value>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>A-PRJ</fullName>
            </value>
            <value>
                <fullName>ARB</fullName>
            </value>
            <value>
                <fullName>ARB-DND</fullName>
            </value>
            <value>
                <fullName>ARB-R</fullName>
            </value>
            <value>
                <fullName>ARB-SENT</fullName>
            </value>
            <value>
                <fullName>AR-WIN</fullName>
            </value>
            <value>
                <fullName>BTA</fullName>
            </value>
            <value>
                <fullName>CSP</fullName>
            </value>
            <value>
                <fullName>DME</fullName>
            </value>
            <value>
                <fullName>DOBI</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>ERR</fullName>
            </value>
            <value>
                <fullName>FES</fullName>
            </value>
            <value>
                <fullName>FTP</fullName>
            </value>
            <value>
                <fullName>H-ZEL</fullName>
            </value>
            <value>
                <fullName>IDR-APP</fullName>
            </value>
            <value>
                <fullName>IDR FEE PAID</fullName>
            </value>
            <value>
                <fullName>IDR-NEG</fullName>
            </value>
            <value>
                <fullName>IDR-PAID</fullName>
            </value>
            <value>
                <fullName>IDR-WIN</fullName>
            </value>
            <value>
                <fullName>INP</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>I-REF</fullName>
            </value>
            <value>
                <fullName>LOP</fullName>
            </value>
            <value>
                <fullName>LOP-N</fullName>
            </value>
            <value>
                <fullName>LVM</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>SPB</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>P-NAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/AR_Injection_Archival__c.object-meta.xml
<CustomObject>
    <label>AR Injection Status Archival</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Injection Status Archivals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Age_by_DOS__c.field-meta.xml
<CustomField>
    <fullName>AR_Age_by_DOS__c</fullName>
    <label>Age by DOS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Charge_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Charge_Status__c</fullName>
    <label>Charge Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Credit_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Credit_Id__c</fullName>
    <label>Credit Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_DOS__c.field-meta.xml
<CustomField>
    <fullName>AR_DOS__c</fullName>
    <label>DOS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Entered_Date__c.field-meta.xml
<CustomField>
    <fullName>AR_Entered_Date__c</fullName>
    <label>Entered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Location_Id__c</fullName>
    <label>Location Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Metadata_Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>AR_Metadata_Time_Stamp__c</fullName>
    <label>Metadata Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>AR_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AR Injection Status Archivals</relationshipLabel>
    <relationshipName>AR_Injection_Status_Archivals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Patient_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>AR_Patient_Adjustments__c</fullName>
    <label>Patient Adjustments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>AR_Patient_Id__c</fullName>
    <label>Patient Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Patient_Payments__c.field-meta.xml
<CustomField>
    <fullName>AR_Patient_Payments__c</fullName>
    <label>Patient Payments</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Payer__c.field-meta.xml
<CustomField>
    <fullName>AR_Payer__c</fullName>
    <label>Payer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Payment_Variance__c.field-meta.xml
<CustomField>
    <fullName>AR_Payment_Variance__c</fullName>
    <label>Payment [Variance]</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Priority_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Priority_Status__c</fullName>
    <label>Priority Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Procedure_Description__c.field-meta.xml
<CustomField>
    <fullName>AR_Procedure_Description__c</fullName>
    <label>Procedure Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Responsibile_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Responsibile_Party_Name__c</fullName>
    <label>Responsibile Party Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Team_Name__c.field-meta.xml
<CustomField>
    <fullName>AR_Team_Name__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/AR_Un_Applied__c.field-meta.xml
<CustomField>
    <fullName>AR_Un_Applied__c</fullName>
    <label>Un-Applied</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Injection_Archival__c/fields/Injection_Status__c.field-meta.xml
<CustomField>
    <fullName>Injection_Status__c</fullName>
    <label>Injection Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AR_AccountsReceivableArchivalHandler.cls
/*public class AR_AccountsReceivableArchivalHandler {

    // === EXISTING HANDLER LOGIC ===
    public static void handleArchival(List<AR_Accounts_Receivable__c> newList, Map<Id, AR_Accounts_Receivable__c> oldMap) {
        if (newList == null || newList.isEmpty()) return;

        List<AR_Injection_Archival__c> archivalRecords = new List<AR_Injection_Archival__c>();
        List<Id> recordsToDeleteIds = new List<Id>();
        Set<Id> ownerIds = new Set<Id>();

        // Collect owner IDs
        for (AR_Accounts_Receivable__c newRec : newList) {
            AR_Accounts_Receivable__c oldRec = (oldMap != null) ? oldMap.get(newRec.Id) : null;
            if (newRec.Injection_Status__c == 'ACC' && (oldRec == null || oldRec.Injection_Status__c != 'ACC')) {
                if (newRec.OwnerId != null) ownerIds.add(newRec.OwnerId);
            }
        }

        Map<Id, User> ownerMap = new Map<Id, User>();
        if (!ownerIds.isEmpty()) {
            ownerMap = new Map<Id, User>([
                SELECT Id, Name FROM User WHERE Id IN :ownerIds
            ]);
        }

        // Build archival records
        for (AR_Accounts_Receivable__c newRec : newList) {
            AR_Accounts_Receivable__c oldRec = (oldMap != null) ? oldMap.get(newRec.Id) : null;

            if (newRec.Injection_Status__c == 'ACC' && (oldRec == null || oldRec.Injection_Status__c != 'ACC')) {
                AR_Injection_Archival__c arch = new AR_Injection_Archival__c();

                // === Field mappings ===
                arch.AR_Debit_Id__c = newRec.AR_Debit_Id__c;
                arch.AR_Business_Entity_Id__c = newRec.AR_Business_Entity_Id__c;
                arch.AR_Patient_Id__c = newRec.AR_Patient_Id__c;
                arch.AR_Age_by_First_Billed__c = newRec.AR_Age_by_First_Billed__c;
                arch.AR_Age_by_Last_Billed__c = newRec.AR_Age_by_Last_Billed__c;
                arch.AR_Age_by_DOS__c = newRec.AR_Age_by_DOS__c;
                arch.AR_Balance__c = newRec.AR_Balance__c;
                arch.AR_Un_Applied__c = newRec.AR_Un_Applied__c;
                arch.AR_Responsibility__c = newRec.AR_Responsibility__c;
                arch.AR_Responsibility_Type__c = newRec.AR_Responsibility_Type__c;
                arch.AR_Location_Id__c = newRec.AR_Location_Id__c;
                arch.AR_Provider_Id__c = newRec.AR_Provider_Id__c;
                arch.AR_Payer_Id__c = newRec.AR_Payer_Id__c;
                arch.AR_Attending_Provider_Id__c = newRec.AR_Attending_Provider_Id__c;
                arch.AR_Policy_Type__c = newRec.AR_Policy_Type__c;
                arch.AR_Insurance_Profile__c = newRec.AR_Insurance_Profile__c;
                arch.AR_Effective_Date__c = newRec.AR_Effective_Date__c;
                arch.AR_Entered_Date__c = newRec.AR_Entered_Date__c;
                arch.AR_Procedure_Code__c = newRec.AR_Procedure_Code__c;
                arch.AR_Procedure_Description__c = newRec.AR_Procedure_Description__c;
                arch.AR_Modifier1_Code__c = newRec.AR_Modifier1_Code__c;
                arch.AR_Diagnosis1_Code__c = newRec.AR_Diagnosis1_Code__c;
                arch.AR_Units__c = newRec.AR_Units__c;
                arch.AR_Value_Balance__c = newRec.AR_Value_Balance__c;
                arch.AR_Insurance_Payments__c = newRec.AR_Insurance_Payments__c;
                arch.AR_Patient_Payments__c = newRec.AR_Patient_Payments__c;
                arch.AR_Insurance_Adjustments__c = newRec.AR_Insurance_Adjustments__c;
                arch.AR_Patient_Adjustments__c = newRec.AR_Patient_Adjustments__c;
                arch.AR_Amount__c = newRec.AR_Amount__c;
                arch.AR_Transaction_Status__c = newRec.AR_Transaction_Status__c;
                arch.AR_Transaction_Type__c = newRec.AR_Transaction_Type__c;
                arch.AR_Charge_Status__c = newRec.AR_Charge_Status__c;
                arch.AR_Responsibile_Party_Name__c = newRec.AR_Responsibile_Party_Name__c;
                arch.AR_Responsibile_Party_Relationship__c = newRec.AR_Responsibile_Party_Relationship__c;
                arch.AR_Last_Claim_Id__c = newRec.AR_Last_Claim_Id__c;
                arch.AR_Last_Billed_Date__c = newRec.AR_Last_Billed_Date__c;
                arch.AR_DOS__c = newRec.AR_DOS__c;
                arch.AR_Metadata_Time_Stamp__c = newRec.AR_Metadata_Time_Stamp__c;
                arch.AR_Patient_Account__c = newRec.AR_Patient_Account__c;
                arch.AR_Payer__c = newRec.AR_Payer__c;
                arch.AR_Provider__c = newRec.AR_Provider__c;
                arch.AR_Financial_Class__c = newRec.AR_Financial_Class__c;
                arch.AR_Location_Name__c = newRec.AR_Location_Name__c;
                arch.AR_Date_Worked__c = newRec.AR_Date_Worked__c;
                arch.Follow_Up_Date__c = newRec.Follow_Up_Date__c;
                arch.AR_Note__c = newRec.AR_Note__c;
                arch.AR_Denial_Date__c = newRec.AR_Denial_Date__c;
                arch.AR_Expected_Amount__c = newRec.AR_Expected_Amount__c;
                arch.Adjustment_Code_1_Description__c = newRec.Adjustment_Code_1_Description__c;
                arch.AR_External_Id__c = newRec.AR_External_Id__c;
                arch.AR_Credit_Id__c = newRec.AR_Credit_Id__c;
                arch.AR_Patient_Guid__c = newRec.AR_Patient_Guid__c;
                arch.Injection_Status__c = String.valueOf(newRec.Injection_Status__c);
                arch.AR_Priority_Status__c = String.valueOf(newRec.AR_Priority_Status__c);
                arch.AR_Team_Name__c = newRec.AR_Team_Name__c;
                arch.AR_Payment_Variance__c = String.valueOf(newRec.AR_Payment_Variance__c);

                // Owner Name
                User ownerRec = ownerMap.get(newRec.OwnerId);
                arch.AR_Assignment__c = (ownerRec != null) ? ownerRec.Name : null;

                archivalRecords.add(arch);
                recordsToDeleteIds.add(newRec.Id);
            }
        }

        if (!archivalRecords.isEmpty()) {
            insert archivalRecords;
            deleteRecordsAsync(recordsToDeleteIds);
        }
    }

    // === FUTURE METHOD for async delete ===
    @future
    public static void deleteRecordsAsync(List<Id> recordIds) {
        try {
            if (recordIds == null || recordIds.isEmpty()) return;
            List<AR_Accounts_Receivable__c> toDelete = [
                SELECT Id FROM AR_Accounts_Receivable__c WHERE Id IN :recordIds
            ];
            if (!toDelete.isEmpty()) {
                delete toDelete;
            }
        } catch (Exception e) {
            System.debug('Async delete failed: ' + e.getMessage());
        }
    }

    // === INVOCABLE WRAPPER (for Flow) ===
    public class ArchivalRequest {
        @InvocableVariable(required=true)
        public Id recordId;
    }

    @InvocableMethod(
        
        description='Archives AR_Accounts_Receivable__c records where Injection_Status__c = ACC'
    )
    public static void archiveFromFlow(List<ArchivalRequest> requests) {
        if (requests == null || requests.isEmpty()) return;

        // Extract Ids from requests
        List<Id> recordIds = new List<Id>();
        for (ArchivalRequest req : requests) {
            if (req != null && req.recordId != null) {
                recordIds.add(req.recordId);
            }
        }

        if (recordIds.isEmpty()) return;

        // Query records and reuse handler
        List<AR_Accounts_Receivable__c> accList = [
            SELECT Id, OwnerId, Injection_Status__c, AR_Priority_Status__c,
                   AR_Debit_Id__c, AR_Business_Entity_Id__c, AR_Patient_Id__c,
                   AR_Age_by_First_Billed__c, AR_Age_by_Last_Billed__c, AR_Age_by_DOS__c,
                   AR_Balance__c, AR_Un_Applied__c, AR_Responsibility__c, AR_Responsibility_Type__c,
                   AR_Location_Id__c, AR_Provider_Id__c, AR_Payer_Id__c, AR_Attending_Provider_Id__c,
                   AR_Policy_Type__c, AR_Insurance_Profile__c, AR_Effective_Date__c, AR_Entered_Date__c,
                   AR_Procedure_Code__c, AR_Procedure_Description__c, AR_Modifier1_Code__c,
                   AR_Diagnosis1_Code__c, AR_Units__c, AR_Value_Balance__c, AR_Insurance_Payments__c,
                   AR_Patient_Payments__c, AR_Insurance_Adjustments__c, AR_Patient_Adjustments__c,
                   AR_Amount__c, AR_Transaction_Status__c, AR_Transaction_Type__c, AR_Charge_Status__c,
                   AR_Responsibile_Party_Name__c, AR_Responsibile_Party_Relationship__c,
                   AR_Last_Claim_Id__c, AR_Last_Billed_Date__c, AR_DOS__c,
                   AR_Metadata_Time_Stamp__c, AR_Patient_Account__c, AR_Payer__c, AR_Provider__c,
                   AR_Financial_Class__c, AR_Location_Name__c, AR_Date_Worked__c,
                   Follow_Up_Date__c, AR_Note__c, AR_Denial_Date__c, AR_Expected_Amount__c,
                   Adjustment_Code_1_Description__c, AR_External_Id__c, AR_Credit_Id__c, AR_Patient_Guid__c,
                   AR_Team_Name__c, AR_Payment_Variance__c
            FROM AR_Accounts_Receivable__c
            WHERE Id IN :recordIds
        ];

        // Call existing archival logic
        handleArchival(accList, new Map<Id, AR_Accounts_Receivable__c>());
    }
}*/
public class AR_AccountsReceivableArchivalHandler {

    // === EXISTING HANDLER LOGIC ===
    public static void handleArchival(List<AR_Accounts_Receivable__c> newList, Map<Id, AR_Accounts_Receivable__c> oldMap) {
        if (newList == null || newList.isEmpty()) return;

        // ✅ New: Define archival statuses
        Set<String> archivalStatuses = new Set<String>{ 'ACC', 'A-PRJ', 'PLN', 'SPB', 'SPR', 'P-NAP' };

        List<AR_Injection_Archival__c> archivalRecords = new List<AR_Injection_Archival__c>();
        List<Id> recordsToDeleteIds = new List<Id>();
        Set<Id> ownerIds = new Set<Id>();

        // === Collect owner IDs ===
        for (AR_Accounts_Receivable__c newRec : newList) {
            AR_Accounts_Receivable__c oldRec = (oldMap != null) ? oldMap.get(newRec.Id) : null;

            // ✅ Updated condition
            if (archivalStatuses.contains(newRec.Injection_Status__c) &&
                (oldRec == null || !archivalStatuses.contains(oldRec.Injection_Status__c))) {
                if (newRec.OwnerId != null) ownerIds.add(newRec.OwnerId);
            }
        }

        Map<Id, User> ownerMap = new Map<Id, User>();
        if (!ownerIds.isEmpty()) {
            ownerMap = new Map<Id, User>([
                SELECT Id, Name FROM User WHERE Id IN :ownerIds
            ]);
        }

        // === Build archival records ===
        for (AR_Accounts_Receivable__c newRec : newList) {
            AR_Accounts_Receivable__c oldRec = (oldMap != null) ? oldMap.get(newRec.Id) : null;

            // ✅ Updated condition again
            if (archivalStatuses.contains(newRec.Injection_Status__c) &&
                (oldRec == null || !archivalStatuses.contains(oldRec.Injection_Status__c))) {

                AR_Injection_Archival__c arch = new AR_Injection_Archival__c();

                // === Field mappings ===
                arch.AR_Debit_Id__c = newRec.AR_Debit_Id__c;
                arch.AR_Business_Entity_Id__c = newRec.AR_Business_Entity_Id__c;
                arch.AR_Patient_Id__c = newRec.AR_Patient_Id__c;
                arch.AR_Age_by_First_Billed__c = newRec.AR_Age_by_First_Billed__c;
                arch.AR_Age_by_Last_Billed__c = newRec.AR_Age_by_Last_Billed__c;
                arch.AR_Age_by_DOS__c = newRec.AR_Age_by_DOS__c;
                arch.AR_Balance__c = newRec.AR_Balance__c;
                arch.AR_Un_Applied__c = newRec.AR_Un_Applied__c;
                arch.AR_Responsibility__c = newRec.AR_Responsibility__c;
                arch.AR_Responsibility_Type__c = newRec.AR_Responsibility_Type__c;
                arch.AR_Location_Id__c = newRec.AR_Location_Id__c;
                arch.AR_Provider_Id__c = newRec.AR_Provider_Id__c;
                arch.AR_Payer_Id__c = newRec.AR_Payer_Id__c;
                arch.AR_Attending_Provider_Id__c = newRec.AR_Attending_Provider_Id__c;
                arch.AR_Policy_Type__c = newRec.AR_Policy_Type__c;
                arch.AR_Insurance_Profile__c = newRec.AR_Insurance_Profile__c;
                arch.AR_Effective_Date__c = newRec.AR_Effective_Date__c;
                arch.AR_Entered_Date__c = newRec.AR_Entered_Date__c;
                arch.AR_Procedure_Code__c = newRec.AR_Procedure_Code__c;
                arch.AR_Procedure_Description__c = newRec.AR_Procedure_Description__c;
                arch.AR_Modifier1_Code__c = newRec.AR_Modifier1_Code__c;
                arch.AR_Diagnosis1_Code__c = newRec.AR_Diagnosis1_Code__c;
                arch.AR_Units__c = newRec.AR_Units__c;
                arch.AR_Value_Balance__c = newRec.AR_Value_Balance__c;
                arch.AR_Insurance_Payments__c = newRec.AR_Insurance_Payments__c;
                arch.AR_Patient_Payments__c = newRec.AR_Patient_Payments__c;
                arch.AR_Insurance_Adjustments__c = newRec.AR_Insurance_Adjustments__c;
                arch.AR_Patient_Adjustments__c = newRec.AR_Patient_Adjustments__c;
                arch.AR_Amount__c = newRec.AR_Amount__c;
                arch.AR_Transaction_Status__c = newRec.AR_Transaction_Status__c;
                arch.AR_Transaction_Type__c = newRec.AR_Transaction_Type__c;
                arch.AR_Charge_Status__c = newRec.AR_Charge_Status__c;
                arch.AR_Responsibile_Party_Name__c = newRec.AR_Responsibile_Party_Name__c;
                arch.AR_Responsibile_Party_Relationship__c = newRec.AR_Responsibile_Party_Relationship__c;
                arch.AR_Last_Claim_Id__c = newRec.AR_Last_Claim_Id__c;
                arch.AR_Last_Billed_Date__c = newRec.AR_Last_Billed_Date__c;
                arch.AR_DOS__c = newRec.AR_DOS__c;
                arch.AR_Metadata_Time_Stamp__c = newRec.AR_Metadata_Time_Stamp__c;
                arch.AR_Patient_Account__c = newRec.AR_Patient_Account__c;
                arch.AR_Payer__c = newRec.AR_Payer__c;
                arch.AR_Provider__c = newRec.AR_Provider__c;
                arch.AR_Financial_Class__c = newRec.AR_Financial_Class__c;
                arch.AR_Location_Name__c = newRec.AR_Location_Name__c;
                arch.AR_Date_Worked__c = newRec.AR_Date_Worked__c;
                arch.Follow_Up_Date__c = newRec.Follow_Up_Date__c;
                arch.AR_Note__c = newRec.AR_Note__c;
                arch.AR_Denial_Date__c = newRec.AR_Denial_Date__c;
                arch.AR_Expected_Amount__c = newRec.AR_Expected_Amount__c;
                arch.Adjustment_Code_1_Description__c = newRec.Adjustment_Code_1_Description__c;
                arch.AR_External_Id__c = newRec.AR_External_Id__c;
                arch.AR_Credit_Id__c = newRec.AR_Credit_Id__c;
                arch.AR_Patient_Guid__c = newRec.AR_Patient_Guid__c;
                arch.Injection_Status__c = String.valueOf(newRec.Injection_Status__c);
                arch.AR_Priority_Status__c = String.valueOf(newRec.AR_Priority_Status__c);
                arch.AR_Team_Name__c = newRec.AR_Team_Name__c;
                arch.AR_Payment_Variance__c = String.valueOf(newRec.AR_Payment_Variance__c);

                // === Owner Name ===
                User ownerRec = ownerMap.get(newRec.OwnerId);
                arch.AR_Assignment__c = (ownerRec != null) ? ownerRec.Name : null;

                archivalRecords.add(arch);
                recordsToDeleteIds.add(newRec.Id);
            }
        }

        if (!archivalRecords.isEmpty()) {
            insert archivalRecords;
            deleteRecordsAsync(recordsToDeleteIds);
        }
    }

    // === FUTURE METHOD for async delete ===
    @future
    public static void deleteRecordsAsync(List<Id> recordIds) {
        try {
            if (recordIds == null || recordIds.isEmpty()) return;
            List<AR_Accounts_Receivable__c> toDelete = [
                SELECT Id FROM AR_Accounts_Receivable__c WHERE Id IN :recordIds
            ];
            if (!toDelete.isEmpty()) {
                delete toDelete;
            }
        } catch (Exception e) {
            System.debug('Async delete failed: ' + e.getMessage());
        }
    }

    // === INVOCABLE WRAPPER (for Flow) ===
    public class ArchivalRequest {
        @InvocableVariable(required=true)
        public Id recordId;
    }

    @InvocableMethod(
        description='Archives AR_Accounts_Receivable__c records where Injection_Status__c in (ACC, A-PRJ, PLN, SPB, SPR, P-NAP)'
    )
    public static void archiveFromFlow(List<ArchivalRequest> requests) {
        if (requests == null || requests.isEmpty()) return;

        List<Id> recordIds = new List<Id>();
        for (ArchivalRequest req : requests) {
            if (req != null && req.recordId != null) {
                recordIds.add(req.recordId);
            }
        }

        if (recordIds.isEmpty()) return;

        List<AR_Accounts_Receivable__c> accList = [
            SELECT Id, OwnerId, Injection_Status__c, AR_Priority_Status__c,
                   AR_Debit_Id__c, AR_Business_Entity_Id__c, AR_Patient_Id__c,
                   AR_Age_by_First_Billed__c, AR_Age_by_Last_Billed__c, AR_Age_by_DOS__c,
                   AR_Balance__c, AR_Un_Applied__c, AR_Responsibility__c, AR_Responsibility_Type__c,
                   AR_Location_Id__c, AR_Provider_Id__c, AR_Payer_Id__c, AR_Attending_Provider_Id__c,
                   AR_Policy_Type__c, AR_Insurance_Profile__c, AR_Effective_Date__c, AR_Entered_Date__c,
                   AR_Procedure_Code__c, AR_Procedure_Description__c, AR_Modifier1_Code__c,
                   AR_Diagnosis1_Code__c, AR_Units__c, AR_Value_Balance__c, AR_Insurance_Payments__c,
                   AR_Patient_Payments__c, AR_Insurance_Adjustments__c, AR_Patient_Adjustments__c,
                   AR_Amount__c, AR_Transaction_Status__c, AR_Transaction_Type__c, AR_Charge_Status__c,
                   AR_Responsibile_Party_Name__c, AR_Responsibile_Party_Relationship__c,
                   AR_Last_Claim_Id__c, AR_Last_Billed_Date__c, AR_DOS__c,
                   AR_Metadata_Time_Stamp__c, AR_Patient_Account__c, AR_Payer__c, AR_Provider__c,
                   AR_Financial_Class__c, AR_Location_Name__c, AR_Date_Worked__c,
                   Follow_Up_Date__c, AR_Note__c, AR_Denial_Date__c, AR_Expected_Amount__c,
                   Adjustment_Code_1_Description__c, AR_External_Id__c, AR_Credit_Id__c, AR_Patient_Guid__c,
                   AR_Team_Name__c, AR_Payment_Variance__c
            FROM AR_Accounts_Receivable__c
            WHERE Id IN :recordIds
        ];

        handleArchival(accList, new Map<Id, AR_Accounts_Receivable__c>());
    }
}