force-app/main/default/objects/CareCloud_Charge__c/CareCloud_Charge__c.object-meta.xml
<CustomObject>
    <label>CareCloud Charge</label>
    <nameField>
        <label>CareCloud Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CareCloud Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareCloud_Charge__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CareCloud Charges</relationshipLabel>
    <relationshipName>CareCloud_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/CareCloud_Charges_Id__c.field-meta.xml
<CustomField>
    <fullName>CareCloud_Charges_Id__c</fullName>
    <externalId>true</externalId>
    <label>CareCloud Charges Id</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Diagnosis_Code_s__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Code_s__c</fullName>
    <label>Diagnosis Code(s)</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <label>Posting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Non-Posted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Charge__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>simple charge reversal</fullName>
            </value>
            <value>
                <fullName>charge reversal</fullName>
            </value>
            <value>
                <fullName>returned insurance check reversal</fullName>
            </value>
            <value>
                <fullName>returned patient check reversal</fullName>
            </value>
            <value>
                <fullName>simple charge</fullName>
            </value>
            <value>
                <fullName>charge</fullName>
            </value>
            <value>
                <fullName>returned insurance check</fullName>
            </value>
            <value>
                <fullName>returned patient check</fullName>
            </value>
            <value>
                <fullName>insurance adjustment</fullName>
            </value>
            <value>
                <fullName>insurance adjustment refund</fullName>
            </value>
            <value>
                <fullName>insurance adjustment refund reversal</fullName>
            </value>
            <value>
                <fullName>insurance adjustment reversal</fullName>
            </value>
            <value>
                <fullName>insurance payment</fullName>
            </value>
            <value>
                <fullName>insurance payment refund</fullName>
            </value>
            <value>
                <fullName>insurance payment refund reversal</fullName>
            </value>
            <value>
                <fullName>insurance payment reversal</fullName>
            </value>
            <value>
                <fullName>patient adjustment</fullName>
            </value>
            <value>
                <fullName>patient adjustment reversal</fullName>
            </value>
            <value>
                <fullName>patient payment</fullName>
            </value>
            <value>
                <fullName>patient payment refund</fullName>
            </value>
            <value>
                <fullName>patient payment refund reversal</fullName>
            </value>
            <value>
                <fullName>patient payment reversal</fullName>
            </value>
            <value>
                <fullName>withhold</fullName>
            </value>
            <value>
                <fullName>withhold refund</fullName>
            </value>
            <value>
                <fullName>withhold refund reversal</fullName>
            </value>
            <value>
                <fullName>withhold reversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/CareCloud_Payment__c.object-meta.xml
<CustomObject>
    <label>CareCloud Transaction</label>
    <nameField>
        <displayFormat>CCP-{00000000}</displayFormat>
        <label>CareCloud Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CareCloud Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareCloud_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CareCloud_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Attending_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Attending_Provider_Id__c</fullName>
    <label>Attending Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/CareCloud_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>CareCloud_Payment_Id__c</fullName>
    <externalId>true</externalId>
    <label>CareCloud Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>posted</fullName>
            </value>
            <value>
                <fullName>not_posted</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>simple_charge_reversal</fullName>
            </value>
            <value>
                <fullName>charge_reversal</fullName>
            </value>
            <value>
                <fullName>returned_insurance_check_reversal</fullName>
            </value>
            <value>
                <fullName>returned_patient_check_reversal</fullName>
            </value>
            <value>
                <fullName>simple_charge</fullName>
            </value>
            <value>
                <fullName>charge</fullName>
            </value>
            <value>
                <fullName>returned_insurance_check</fullName>
            </value>
            <value>
                <fullName>returned_patient_check</fullName>
            </value>
            <value>
                <fullName>insurance_adjustment</fullName>
            </value>
            <value>
                <fullName>insurance_adjustment_refund</fullName>
            </value>
            <value>
                <fullName>insurance_adjustment_refund_reversal</fullName>
            </value>
            <value>
                <fullName>insurance_adjustment_reversal</fullName>
            </value>
            <value>
                <fullName>insurance_payment</fullName>
            </value>
            <value>
                <fullName>insurance_payment_refund</fullName>
            </value>
            <value>
                <fullName>insurance_payment_refund_reversal</fullName>
            </value>
            <value>
                <fullName>insurance_payment_reversal</fullName>
            </value>
            <value>
                <fullName>patient_adjustment</fullName>
            </value>
            <value>
                <fullName>patient_adjustment_reversal</fullName>
            </value>
            <value>
                <fullName>patient_payment</fullName>
            </value>
            <value>
                <fullName>patient_payment_refund</fullName>
            </value>
            <value>
                <fullName>patient_payment_refund_reversal</fullName>
            </value>
            <value>
                <fullName>patient_payment_reversal</fullName>
            </value>
            <value>
                <fullName>withhold</fullName>
            </value>
            <value>
                <fullName>withhold_refund</fullName>
            </value>
            <value>
                <fullName>withhold_refund_reversal</fullName>
            </value>
            <value>
                <fullName>withhold_reversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Unapplied_Credit__c.field-meta.xml
<CustomField>
    <fullName>Unapplied_Credit__c</fullName>
    <label>Unapplied Credit</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CareCloud_Payment__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCPaymentAndChargeSyncSetting__mdt/CCPaymentAndChargeSyncSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings to define sync behaviour of charges and payments</description>
    <label>CCPaymentAndChargeSyncSetting</label>
    <pluralLabel>CCPaymentAndChargeSyncSettings</pluralLabel>
</CustomObject>

force-app/main/default/classes/PatientChargeDAO.cls
public inherited sharing class PatientChargeDAO {
	
    private final static String CHARGE_TYPE = 'charge';
    private final static String REVERSE_CHARGE_TYPE = 'charge_reversal';
    private final static String PATIENT_PAYMENT_TYPE = 'patient_payment';
    private final static String INSURANCE_PAYMENT_TYPE = 'insurance_payment';
    
    public static CCPaymentAndChargeSyncSetting__mdt getSyncSetting(){
        return CCPaymentAndChargeSyncSetting__mdt.getInstance('IncrementalSync');
    }
    
    public static Boolean isValidTransactionTypes(String transactionType) {
        if (String.isNotBlank(transactionType)) {
            if (
                CHARGE_TYPE == transactionType.toLowerCase()
                ||
                REVERSE_CHARGE_TYPE == transactionType.toLowerCase()
                ||
	            PATIENT_PAYMENT_TYPE == transactionType.toLowerCase()
                ||
                INSURANCE_PAYMENT_TYPE == transactionType.toLowerCase()
            ) {
                return true;
            }
        }
        return false;
    }
    
    public static List<CareCloud_Charge__c> createCharges(String accountId, List<Object> rawCharges) {
		List<CareCloud_Charge__c> charges = new List<CareCloud_Charge__c>();
        if (rawCharges != null && rawCharges.size() > 0) {
            for (Object rawChargeObj: rawCharges) {
                Map<String, Object> rawCharge = (Map<String, Object>) rawChargeObj;
                if (isValidTransactionTypes((String) rawCharge.get('transaction_type'))) {
                    charges.add(
                        new CareCloud_Charge__c (
                            Amount__c = getDecimal(rawCharge.get('amount')),
                            Attending_Provider_Id__c = getInt2String(rawCharge.get('attending_provider_id')),
                            Balance__c = getDecimal(rawCharge.get('balance')),
                            CareCloud_Charges_Id__c = getInt2String(rawCharge.get('id')),
                            Description__c = (String) rawCharge.get('description'),
                            Location_Id__c = getInt2String(rawCharge.get('location_id')),
                            Diagnosis_Code_s__c = (String) rawCharge.get('diagnosis_code(s)'),
                            Procedure_Code__c = (String) rawCharge.get('procedure_code'),
                            Posting_Date__c = formatDatetime((String) rawCharge.get('posting_date')),
                            Provider_Id__c = getInt2String(rawCharge.get('provider_id')),
                            Service_Date__c = rawCharge.get('service_date') != null ? formatDatetime((String) rawCharge.get('service_date')).date() : null,
                            Transaction_Status__c = (String) rawCharge.get('transaction_status'),
                            Transaction_Type__c = (String) rawCharge.get('transaction_type'),
                            Unapplied_Credit__c = getDecimal(rawCharge.get('unapplied_credit')),
                            Units__c = (String) rawCharge.get('units'),
                            Account__c = accountId
                        )
                	);
                }
            }
        }
        return charges;
    }
    
    public static void commitCharges(List<CareCloud_Charge__c> charges) {
    	if (charges.size() > 0) {
        	upsert charges CareCloud_Charges_Id__c;
        }
    }
    
    public static Datetime formatDatetime(String dt) {
        if (String.isBlank(dt)) {
            return null;
        }
        return Datetime.valueOf(dt.substring(0, 18).replace('T', ' '));
    }
    
    // payments
    
    public static List<CareCloud_Payment__c> createPayments(String accountId, List<Object> rawpayments) {
        system.debug(rawpayments);
		List<CareCloud_Payment__c> payments = new List<CareCloud_Payment__c>();
        if (rawpayments != null && rawpayments.size() > 0) {
            for (Object rawPaymentObj: rawpayments) {
                Map<String, Object> rawPayment = (Map<String, Object>) rawPaymentObj;
               if (isValidTransactionTypes((String) rawPayment.get('transaction_type'))) {
                    payments.add(
                        new CareCloud_Payment__c(
                            Amount__c = getDecimal(rawPayment.get('amount')),
                            Attending_Provider_Id__c = getInt2String(rawPayment.get('attending_provider_id')),
                            Balance__c = getDecimal(rawPayment.get('balance')),
                            CareCloud_Payment_Id__c = getInt2String(rawPayment.get('id')),
                            Description__c = (String) rawPayment.get('description'),
                            Location_Id__c = getInt2String(rawPayment.get('location_id')),
                            Posting_Date__c = formatDatetime((String) rawPayment.get('posting_date')),
                            Provider_Id__c = getInt2String(rawPayment.get('provider_id')),
                            Service_Date__c = rawPayment.get('service_date') != null ? formatDatetime((String) rawPayment.get('service_date')).date() : null,
                            Procedure_Code__c = (String) rawPayment.get('procedure_code'),
                            Transaction_Status__c = (String) rawPayment.get('transaction_status'),
                            Transaction_Type__c = (String) rawPayment.get('transaction_type'),
                            Unapplied_Credit__c = getDecimal(rawPayment.get('unapplied_credit')),
                            Units__c = (String) rawPayment.get('units'),
                            Account__c = accountId
                        )
                    );
               }
            }
        }
        return payments;
    }
    
    public static void commitPayments(List<CareCloud_Payment__c> payments) {
    	if (payments.size() > 0) {
        	upsert payments CareCloud_Payment_Id__c;
        }
    }
    
    private static Decimal getDecimal(Object obj) {
        if (obj instanceof String) {
            return Decimal.valueOf((String) obj);
        }
        return (Decimal) obj;
    }
    
    private static String getInt2String(Object obj) {
        if (obj instanceof Integer) {
            return String.valueOf(obj);
        }
        return (String) obj;
    }
}