force-app/main/default/objects/RUL__c/RUL__c.object-meta.xml
<CustomObject>
    <label>RUL</label>
    <nameField>
        <displayFormat>RUL - {0000}</displayFormat>
        <label>RUL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RUL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RUL__c/fields/RUL_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>RUL_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RUL_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RUL__c/fields/RUL_Billed_Charges__c.field-meta.xml
<CustomField>
    <fullName>RUL_Billed_Charges__c</fullName>
    <label>Billed Charges</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RUL__c/fields/RUL_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>RUL_Issue_Type__c</fullName>
    <label>Issue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Medical Records</fullName>
            </value>
            <value>
                <fullName>Authorizations</fullName>
            </value>
            <value>
                <fullName>Dispensing</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Exercise Sheet</fullName>
            </value>
            <value>
                <fullName>LMN/Med Necessity</fullName>
            </value>
            <value>
                <fullName>AOB</fullName>
            </value>
            <value>
                <fullName>Missing Financial Agreement</fullName>
            </value>
            <value>
                <fullName>Coding Query</fullName>
            </value>
            <value>
                <fullName>Coding Query - TeamMD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RUL__c/fields/RUL_Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>RUL_Patient_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Account</description>
    <label>Patient Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RUL&apos;s</relationshipLabel>
    <relationshipName>RUL_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RUL__c/fields/RUL_Status__c.field-meta.xml
<CustomField>
    <fullName>RUL_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignee</fullName>
                <default>true</default>
                <label>Pending Assignee</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Assignor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MorningPendingRecordsEmailSchedulerTest.cls
@isTest
public class MorningPendingRecordsEmailSchedulerTest {

    @isTest
    static void testExecuteMethod() {
        // Create test data: RUL__c records with 'Pending' status
        List<RUL__c> rulRecords = new List<RUL__c>();
        
        // Create a test user to assign RUL__c records
        User testUser = new User(
            Username = 'testuse5658r@example.com',
            Alias = 'testusr',
            lastName ='testusr',
            EmailEncodingKey='ISO-8859-1',
            Email = 'testuser@example.com',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        Account a1= new Account(
        Lastname='Krishna'
        );
            insert a1;

        // Creating some sample RUL__c records
        for (Integer i = 0; i < 3; i++) {
            RUL__c record = new RUL__c(
                RUL_Status__c = 'Pending Assignee',
                RUL_Assigned_To__c = testUser.Id,
               // RUL_Patient_Name__r = new Patient__c(Name = 'Patient ' + i),
                RUL_Issue_Type__c = 'Insurance',
                RUL_Billed_Charges__c=5,
                RUL_Patient_Name__c=a1.Id
                
            );
            rulRecords.add(record);
        }
        insert rulRecords;

        // Create an instance of the scheduler class and invoke the execute method
        Test.startTest();
        MorningPendingRecordsEmailScheduler scheduler = new MorningPendingRecordsEmailScheduler();
         EveningAssignedRecordsEmailScheduler scheduler1 = new EveningAssignedRecordsEmailScheduler();
        scheduler.execute(null);  // Passing null for the SchedulableContext
        scheduler1.execute(null);  // Passing null for the SchedulableContext
        Test.stopTest();

    }
}