force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Cancellation_Details_Id__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Details_Id__c</fullName>
    <label>Cancellation Details Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient_Chart_Number__c.field-meta.xml
<CustomField>
    <fullName>Patient_Chart_Number__c</fullName>
    <label>Patient Chart Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Referring_Physician_NPI__c.field-meta.xml
<CustomField>
    <fullName>Referring_Physician_NPI__c</fullName>
    <label>Referring Physician NPI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason_Id__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason_Id__c</fullName>
    <label>Visit Reason Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppointmentCleanupBatchTest.cls
@isTest
public class AppointmentCleanupBatchTest {
    @TestSetup
    public static void dataSetup(){
        List<Appointment__c> appointmentList2Upsert = new List<Appointment__c>();
        Appointment__c app1 = new Appointment__c();
        app1.Care_Cloud_Appointment_Id__c  = '08314725-ba4d-476d-9da8-d1c2bdfb264a';
        app1.Status__c = 'Pending';
        app1.Patient_Chart_Number__c = '4303';
        app1.Location_Id__c = String.valueOf(30232);
        app1.Cancellation_Details_Id__c = '';
        app1.Referring_Physician_NPI__c = '';
        app1.Visit_Reason_Id__c  = String.valueOf(95620);
        String start_time = String.valueOf(Date.today().addDays(+10))+'T09:00:00-04:00';
        DateTime dt = DateTime.ValueofGmt(start_time.replace('T', ' '));
        app1.Appointment_Date_Time__c  = dt;
        app1.Provider_Id__c = '25288';
        appointmentList2Upsert.add(app1);
        
        Appointment__c app2 = new Appointment__c();
        app2.Care_Cloud_Appointment_Id__c  = '670fc26c-c68f-4c98-a3b3-c14faea8b1bb';
        app2.Status__c = 'Pending';
        app2.Patient_Chart_Number__c = '228167925';
        app2.Location_Id__c = String.valueOf(30232);
        app2.Cancellation_Details_Id__c = '';
        app2.Referring_Physician_NPI__c = '1265569255';
        app2.Visit_Reason_Id__c  = String.valueOf(95620);
        app2.Appointment_Date_Time__c  = dt;
        app2.Provider_Id__c = '25284';        
        appointmentList2Upsert.add(app2);
        
        insert appointmentList2Upsert;
        
    }

    @isTest static void testAppointmentCleanupBatch(){
        SingleRequestMock accessTokenResp = new SingleRequestMock(200, 'Complete', '{"access_token" : "1234567890"}', null);
        SingleRequestMock validAppointmentResp = new SingleRequestMock(200, 'Complete', '', null);
        SingleRequestMock invalidAppointmentResp = new SingleRequestMock(404, 'Not Found', '', null);

        Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String,HttpCalloutMock>();
        endpoint2TestResp.put('https://api.carecloud.com/oauth2/access_token', accessTokenResp);
        endpoint2TestResp.put('https://api.carecloud.com/v2/appointments/08314725-ba4d-476d-9da8-d1c2bdfb264a', validAppointmentResp);
        endpoint2TestResp.put('https://api.carecloud.com/v2/appointments/670fc26c-c68f-4c98-a3b3-c14faea8b1bb', invalidAppointmentResp);

        HttpCalloutMock multiCalloutMock = new MultiRequestMock(endpoint2TestResp);

        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        Test.startTest();
        AppointmentCleanupBatchScheduler sch = new AppointmentCleanupBatchScheduler();
        sch.execute(null);
        Test.stopTest();
    }
}