force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Cancellation_Details_Id__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Details_Id__c</fullName>
    <label>Cancellation Details Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Comments__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Comments__c</fullName>
    <label>Care Cloud Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Patient_Id__c</fullName>
    <label>Care Cloud Patient Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Email__c.field-meta.xml
<CustomField>
    <fullName>Location_Email__c</fullName>
    <label>Location Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient_Chart_Number__c.field-meta.xml
<CustomField>
    <fullName>Patient_Chart_Number__c</fullName>
    <label>Patient Chart Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Reviews_Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_Reviews_Business_ID__c</fullName>
    <label>Provider Reviews Business ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Provider_Specialty__c</fullName>
    <label>Provider Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acupuncturist</fullName>
            </value>
            <value>
                <fullName>Chiropractor</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle Surgery</fullName>
            </value>
            <value>
                <fullName>Multi-Specialty</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Occupational Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgery</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgeryofthe Spine</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Physical Therapist</fullName>
            </value>
            <value>
                <fullName>Physical Therapy</fullName>
            </value>
            <value>
                <fullName>Physical Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Referring_Physician_NPI__c.field-meta.xml
<CustomField>
    <fullName>Referring_Physician_NPI__c</fullName>
    <label>Referring Physician NPI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason__c</fullName>
    <label>Visit Reason</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason_Id__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason_Id__c</fullName>
    <label>Visit Reason Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/CareCloud_Information__c.object-meta.xml
<CustomObject>
    <description>CareCloud Providers and Locations</description>
    <label>CareCloud Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CareCloud Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CareCloud_Information__c/fields/Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_ID__c</fullName>
    <label>Business ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/fields/CareCloud_Id__c.field-meta.xml
<CustomField>
    <fullName>CareCloud_Id__c</fullName>
    <externalId>true</externalId>
    <label>CareCloud Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acupuncturist</fullName>
            </value>
            <value>
                <fullName>Chiropractor</fullName>
            </value>
            <value>
                <fullName>Durable Medical Equipment &amp; Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Foot &amp; Ankle Surgery</fullName>
            </value>
            <value>
                <fullName>Multi-Specialty</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Occupational Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgery</fullName>
            </value>
            <value>
                <fullName>Orthopaedic Surgeryofthe Spine</fullName>
            </value>
            <value>
                <fullName>Pain Medicine</fullName>
            </value>
            <value>
                <fullName>Physical Therapist</fullName>
            </value>
            <value>
                <fullName>Physical Therapy</fullName>
            </value>
            <value>
                <fullName>Physical Therapy Assistant</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Sports Medicine</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/fields/User_Record__c.field-meta.xml
<CustomField>
    <fullName>User_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Record</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CareCloud_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareCloud_Information__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/CareCloud_Information__c/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

force-app/main/default/classes/AppointmentSyncBatchCallout.cls
global class AppointmentSyncBatchCallout implements Database.Batchable<String>, Database.AllowsCallouts, Database.Stateful {
    private Set<String> noPatientAppointmentId = new Set<String>();
    
    Map<String, CareCloud_Information__c> providerMap = new Map<String, CareCloud_Information__c>();
    Map<String, CareCloud_Information__c> locationMap = new Map<String, CareCloud_Information__c>();
    Map<String, CareCloud_Information__c> visitReasonMap = new Map<String, CareCloud_Information__c>();
    
    String query;
    String start_date;
    String end_date;
    
    global AppointmentSyncBatchCallout(){
        this.start_date = String.valueOf(Date.today().addDays(-10)).removeEnd(' 00:00:00');
        this.end_date = String.valueOf(Date.today().addDays(10)).removeEnd(' 00:00:00');
    }
    
    global AppointmentSyncBatchCallout(Integer startOffset, Integer endOffset){        
        this.start_date = String.valueOf(Date.today().addDays(startOffset)).removeEnd(' 00:00:00');
        this.end_date = String.valueOf(Date.today().addDays(endOffset)).removeEnd(' 00:00:00');
    }
    
    global Iterable<String> start(Database.BatchableContext BC) {
        for(CareCloud_Information__c ccInfo : [SELECT Id, Name, CareCloud_Id__c, RecordType.Name, Email__c, Business_ID__c, Specialty__c, User_Record__c FROM CareCloud_Information__c]){
            switch on ccInfo.RecordType.Name {
                when 'Provider' {
                    providerMap.put(ccInfo.CareCloud_Id__c.replace('P-', ''), ccInfo);
                }
                when 'Location' {
                    locationMap.put(ccInfo.CareCloud_Id__c.replace('L-', ''), ccInfo);
                }
                when 'Visit Reason' {
                    visitReasonMap.put(ccInfo.CareCloud_Id__c.replace('VR-', ''), ccInfo);
                }
            }
        }
        
        HttpResponse apptResp;
        Integer retryCount = 1;
        do{
            apptResp = CareCloudAPIHelper.fetchApointments(this.start_date, this.end_date, '1');
            retryCount++;
        }while(apptResp.getStatusCode() != 200 && retryCount <= 5);
        
        if(apptResp.getStatusCode() != 200){
            return new List<String>();
        }
        
        String headerKeys = apptResp.getHeader('link');
        
        if(headerKeys == null){
            return new List<String>();
        }
        
        Integer totalPages = CareCloudAPIHelper.getTotalPages(headerKeys);
        
        System.debug('Total pages :'+totalPages);
        
        List<String> iterations = new List<String>();
        for(Integer i = 1; i <= totalPages; i++ ){
            iterations.add(String.valueOf(i));
        }
        
        return iterations;
    }

    global void execute(Database.BatchableContext BC, List<String> scope){
        List<Appointment__c> appts = new List<Appointment__c>();
        
        for(String pageNo : scope){
            System.debug('Current Page Number :'+ pageNo);
            
            HttpResponse apptResp = CareCloudAPIHelper.fetchApointments(this.start_date, this.end_date, pageNo);
            
            if(apptResp.getStatusCode() != 200){
                continue;
            }
            
            Set<String> ccPatientIds = new Set<String>();
            List<AppointmentJSONResponse> respAppointments = AppointmentJSONResponse.parse(apptResp.getBody());
            
            System.debug('Number of appointments :'+ respAppointments.size());
            
            for(AppointmentJSONResponse appointment : respAppointments) {
                if (String.isBlank(appointment.Appointment.patient.id)) {
                    noPatientAppointmentId.add(appointment.Appointment.id);
                }else{
                    ccPatientIds.add(appointment.Appointment.patient.id);
                }
            }
            
            Map<String, Account> patientIdToAccountMap = new Map<String, Account>();
            
            if(!ccPatientIds.isEmpty()){
                for(Account acc : [SELECT Id,Name,CareCloud_Patient_Id__c FROM Account WHERE CareCloud_Patient_Id__c in: ccPatientIds]){
                    patientIdToAccountMap.put(acc.CareCloud_Patient_Id__c, acc);
                }
            }
            
            for(AppointmentJSONResponse appointment : respAppointments){
                Appointment__c appRecord = new Appointment__c();
                appRecord.Care_Cloud_Appointment_Id__c  = appointment.Appointment.id;
                appRecord.Status__c = appointment.Appointment.appointment_status.Name;
                appRecord.Patient_Chart_Number__c = appointment.Appointment.patient.chart_number;
                appRecord.Location_Id__c = String.valueOf(appointment.Appointment.location.id);
                appRecord.Cancellation_Details_Id__c = appointment.Appointment.cancellation_details.id;
                appRecord.Care_Cloud_Comments__c = appointment.Appointment.comments;
                appRecord.Referring_Physician_NPI__c = appointment.Appointment.referring_physician_npi;
                appRecord.Visit_Reason_Id__c  = String.valueOf(appointment.Appointment.visit_reason_id);
                appRecord.Care_Cloud_Patient_Id__c = appointment.Appointment.patient.id;
                String start_time = appointment.Appointment.start_time;
                DateTime dt = DateTime.ValueofGmt(start_time.replace('T', ' '));
                Integer timezoneDiff = Integer.valueOf(appointment.Appointment.start_time.split('-')[appointment.Appointment.start_time.split('-').size() - 1].split(':')[0]);
                appRecord.Appointment_Date_Time__c  = dt.addHours(timezoneDiff);
                appRecord.Provider_Id__c = appointment.Appointment.provider_id;
                //Populate UI fields based on metadata values
                if(String.isNotBlank(appRecord.Location_Id__c) && locationMap.containsKey(appRecord.Location_Id__c)){
                    appRecord.Location_Email__c = locationMap.get(appRecord.Location_Id__c).Email__c;
                    appRecord.Location_Name__c = locationMap.get(appRecord.Location_Id__c).Name;
                }
                if(String.isNotBlank(appRecord.Provider_Id__c) && providerMap.containsKey(appRecord.Provider_Id__c)){
                    appRecord.Provider_Name__c = providerMap.get(appRecord.Provider_Id__c).name;
                    appRecord.Provider_Reviews_Business_ID__c = providerMap.get(appRecord.Provider_Id__c).Business_ID__c;
                    appRecord.Provider_Specialty__c = providerMap.get(appRecord.Provider_Id__c).Specialty__c;
                    if(String.isNotBlank(providerMap.get(appRecord.Provider_Id__c).User_Record__c)){
                        appRecord.OwnerId = providerMap.get(appRecord.Provider_Id__c).User_Record__c;
                    }
                }
                appRecord.Visit_Reason__c = String.isNotBlank(appRecord.Visit_Reason_Id__c) && visitReasonMap.containsKey(appRecord.Visit_Reason_Id__c) ? visitReasonMap.get(appRecord.Visit_Reason_Id__c).name : null;
                
                if(String.isNotBlank(appointment.Appointment?.patient?.id) && patientIdToAccountMap.containsKey(appointment.Appointment.patient.id)){
                    appRecord.Patient__c = patientIdToAccountMap.get(appointment.Appointment.patient.id).Id;
                    appRecord.Name = patientIdToAccountMap.get(appointment.Appointment.patient.id).Name + ' - '+appRecord.Visit_Reason__c;
                }
                appts.add(appRecord);
            }
        }
        
        List<Database.upsertResult> apptsUpsertResults = Database.upsert(appts, Appointment__c.Fields.Care_Cloud_Appointment_Id__c, false);
        
        for(Database.upsertResult result : apptsUpsertResults) {
            if(!result.isSuccess()){
                for(Database.Error error : result.getErrors()) {
                    System.debug(error.getMessage());
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        if(!noPatientAppointmentId.isEmpty()) {
            TransactionLogHandler.doHandleCustomException(
            	'No patient id found for few Appointments',
                String.join(new List<String>(noPatientAppointmentId), ','),
                'AppointmentSyncBatchCallout',
                'finish'
            );
        }
    }
}