force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason__c</fullName>
    <label>Visit Reason</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewYearEvaluationBatchJobTest.cls
/*
@isTest()
public class NewYearEvaluationBatchJobTest {
@isTest()
    static void methode1(){
                // Create Accounts
        Account acc1 = new Account(Name = 'Test Account 1',PersonEmail='kkumar@aptimized.com');
        Account acc2 = new Account(Name = 'Test Account 2',PersonEmail='pdurgarao@aptimized.com');
        insert new List<Account>{acc1, acc2};
            
        List<Appointment__c>applist=new List<Appointment__c>();
        Appointment__c app1=new Appointment__c(Name = 'Test Appointment 1',Visit_Reason__c ='New Year Evaluation',Appointment_Date_Time__c = system.today().addDays(15) );
        Appointment__c app2=new Appointment__c(Name = 'Test Appointment 2',Visit_Reason__c ='New Year Evaluation',Appointment_Date_Time__c = system.today().addDays(15));
        Test.startTest();
         NewYearEvaluationBatchJob.methode1();
        Test.stopTest();
        
    }
}*/

@isTest
public class NewYearEvaluationBatchJobTest {
    @isTest
    static void testBatchExecution() {
        // Create Person Accounts
        Account acc1 = new Account(
            FirstName = 'Test',
            LastName = 'Account 1',
            PersonEmail = 'kkumar@aptimized.com',
            NPP_New_Year_Evaluation_Mail_Sent__c = false,
            RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Person Account' LIMIT 1].Id
        );
        Account acc2 = new Account(
            FirstName = 'Test',
            LastName = 'Account 2',
            PersonEmail = 'kkumar@aptimized.com',
            NPP_New_Year_Evaluation_Mail_Sent__c = false,
            RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Person Account' LIMIT 1].Id
        );
        insert new List<Account>{acc1, acc2};

        // Create Appointments associated with Person Accounts
        List<Appointment__c> applist = new List<Appointment__c>();
        Appointment__c app1 = new Appointment__c(
            Name = 'Test Appointment 1',
            Visit_Reason__c = 'New Year Evaluation',
            Appointment_Date_Time__c = System.now().addDays(15),
            Patient__c = acc1.Id
        );
        Appointment__c app2 = new Appointment__c(
            Name = 'Test Appointment 2',
            Visit_Reason__c = 'New Year Evaluation',
            Appointment_Date_Time__c = System.now().addDays(15),
            Patient__c = acc2.Id
        );
        applist.add(app1);
        applist.add(app2);
        insert applist;

        // Run the batch job
        Test.startTest();
        NewYearEvaluationBatchJob batchJob = new NewYearEvaluationBatchJob();
        Database.executeBatch(batchJob, 200); // Execute the batch job with a batch size of 200
        Test.stopTest();

        // Validate the results
        List<Account> updatedAccounts = [SELECT Id, NPP_New_Year_Evaluation_Mail_Sent__c FROM Account WHERE Id IN :new List<Id>{acc1.Id, acc2.Id}];
        
    }
}