force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <formula>DateValue( Appointment_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppointmentCleanupBatch.cls
global class AppointmentCleanupBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    String accessToken;
    Boolean isAllAppointments;
    Integer startOffset;
    Integer endOffset;

    public AppointmentCleanupBatch(){
        isAllAppointments = false;
        accessToken = CareCloudAPIHelper.accessToken;
    }

    public AppointmentCleanupBatch(Boolean isAllAppointments){
        this.isAllAppointments = isAllAppointments;
        accessToken = CareCloudAPIHelper.accessToken;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Appointment_Date__c, Care_Cloud_Appointment_Id__c FROM Appointment__c WHERE Care_Cloud_Appointment_Id__c != NULL AND '+(isAllAppointments ? '' : 'Appointment_Date__c >= LAST_WEEK AND Appointment_Date__c <= NEXT_WEEK AND')+' Status__c = \'Pending\' ORDER BY Appointment_Date__c DESC';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Appointment__c> appointments) {
        if(String.isNotBlank(accessToken)){
            List<Id> invalidAppointments = new List<Id>();
            for(Appointment__c appointment : appointments){
                if(!CareCloudAPIHelper.isValidAppointment(appointment.Care_Cloud_Appointment_Id__c, accessToken)){
                    invalidAppointments.add(appointment.Id);
                }
            }

            if(!invalidAppointments.isEmpty()){
                //delete appointments
                Database.DeleteResult[] deleteResults = Database.delete(invalidAppointments, false);
            }
        }
    } 
    
    global void finish(Database.BatchableContext BC){ 
        if(!Test.isRunningTest()){
            system.enqueueJob(new CareCloudProvidersAndLocationsHelper(false));
        }
    }
}