force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Cancellation_Details_Id__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Details_Id__c</fullName>
    <label>Cancellation Details Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Comments__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Comments__c</fullName>
    <label>Care Cloud Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Patient_Id__c</fullName>
    <label>Care Cloud Patient Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient_Chart_Number__c.field-meta.xml
<CustomField>
    <fullName>Patient_Chart_Number__c</fullName>
    <label>Patient Chart Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Referring_Physician_NPI__c.field-meta.xml
<CustomField>
    <fullName>Referring_Physician_NPI__c</fullName>
    <label>Referring Physician NPI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason_Id__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason_Id__c</fullName>
    <label>Visit Reason Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareCloud_Appointment_Sync__mdt/CareCloud_Appointment_Sync__mdt.object-meta.xml
<CustomObject>
    <description>Add the start date and end date to run Appointment Sync Batch manually for failed cases</description>
    <label>CareCloud Appointment Sync</label>
    <pluralLabel>CareCloud Appointment Syncs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Carecloud_Setup__mdt/Carecloud_Setup__mdt.object-meta.xml
<CustomObject>
    <label>Carecloud Setup</label>
    <pluralLabel>Carecloud Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Carecloud_Setup__mdt/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppointmentSyncBatchCalloutDelta.cls
global with sharing class AppointmentSyncBatchCalloutDelta implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful{
    global Map<String,  AppointmentJSONResponse> appointIdMap = new Map<String,  AppointmentJSONResponse>();
    global List<AppointmentJSONResponse> appointmentList = new List<AppointmentJSONResponse>();
    global List<Appointment__c> appointmentList2Upsert  = new List<Appointment__c>();
    global List<String> appointExistIdList = new List<String>();
    global List<String> ExternalIDs = new List<String>();
    private Set<String> noPatientAppointmentId = new Set<String>();
    String query;

    global Database.queryLocator start(Database.BatchableContext BC) {
        Carecloud_Setup__mdt CareCloudMdt = [Select MasterLabel, Refresh_Token__c FROM Carecloud_Setup__mdt LIMIT 1];
        String accessToken = CareCloudAuthConnection.fetchRefreshAccessToken(CareCloudMdt.Refresh_Token__c);
        System.debug('::: Access Toekn - '+accessToken);

        CareCloud_Appointment_Sync__mdt appSyncRec = [SELECT Id, Start_Date__c, End_Date__c FROM CareCloud_Appointment_Sync__mdt];


        String start_date = String.valueOf(appSyncRec.Start_Date__c);
        String end_date = String.valueOf(appSyncRec.End_Date__c);
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setTimeout(120000);
        request.setEndpoint('https://api.carecloud.com/v2/appointments?end_date='+end_date+'&start_date='+start_date);
        request.setMethod('GET');
        request.setHeader('Authorization', 'Bearer ' + accessToken);

        HttpResponse response = http.send(request);
        while(response.getStatusCode() == 302) {
            request.setEndpoint(response.getHeader('Location'));
            response = new Http().send(request);
        }
        //If Request is Successful, parse the response JSON
        System.debug('::: Response Body = '+response.getBody());
        //System.debug('::: Header Key = '+response.getHeaderKeys());
        System.debug('::: Header Key = '+response.getHeader('Link'));
        String headerKeys = response.getHeader('Link');
        String[] hks = headerKeys.split(',');
        String lastUrl = hks[0].split(';')[0];
        System.debug('::: Last URL = '+lastUrl);
        String s2 = lastUrl.substringAfter('page=').substringBefore('&');
        Integer totalPage = Integer.valueOf(s2);
        System.debug('::: Total Page  = '+totalPage);
        
        appointmentList = AppointmentJSONResponse.parse(response.getBody());
        for(Integer i=1; i<totalPage; i++) {
            Integer currentPage = i+1;
            Http http1 = new Http();
            HttpRequest request1 = new HttpRequest();
            request1.setTimeout(120000);
            request1.setEndpoint('https://api.carecloud.com/v2/appointments?end_date='+end_date+'&page='+currentPage+'&start_date='+start_date);
            request1.setMethod('GET');
            request1.setHeader('Authorization', 'Bearer ' + accessToken);
            
            HttpResponse response1 = http1.send(request1);
            while(response1.getStatusCode() == 302) {
                request1.setEndpoint(response1.getHeader('Location'));
                response1 = new Http().send(request1);
            }
            
            appointmentList.addAll(AppointmentJSONResponse.parse(response1.getBody()));
        }
        System.debug('::: appointmentList = '+appointmentList.size());
        for(AppointmentJSONResponse appointment : appointmentList) {
            appointIdMap.put(appointment.Appointment.id, appointment);
            if (String.isBlank(appointment.Appointment.patient.id)) {
                noPatientAppointmentId.add(appointment.Appointment.id);
            }
        }

        System.debug('::: Start method begins');
        ExternalIDs.addAll(appointIdMap.keySet()); 
        System.debug('::: ExternalIDs Size = '+ExternalIDs.size());
        query = 'SELECT Id, Care_Cloud_Appointment_Id__c FROM Appointment__c where Care_Cloud_Appointment_Id__c IN: ExternalIDs';
        System.debug('::: Query Result = '+Database.query(query));
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Appointment__c> scope){
        system.debug('::: Inside the Execute statement');
        System.debug('::: appointmentList in execute = '+appointmentList);
        //List<AppointmentJSONResponse> appointmentList = AppointmentJSONResponse.parse(response.getBody());
        System.debug('::: Scope Size = '+scope.size());
        for(Appointment__c appointment : scope)
        {
            Appointment__c appRecord = new Appointment__c();
            if(appointIdMap.containsKey(appointment.Care_Cloud_Appointment_Id__c)) { 
                AppointmentJSONResponse  appointmentRec =   appointIdMap.get(appointment.Care_Cloud_Appointment_Id__c);             
                appRecord.Id = appointment.Id;
                appRecord.Care_Cloud_Appointment_Id__c  = appointmentRec.Appointment.id;
                appRecord.Status__c = appointmentRec.Appointment.appointment_status.Name;
                appRecord.Patient_Chart_Number__c = appointmentRec.Appointment.patient.chart_number;
                appRecord.Location_Id__c = String.valueOf(appointmentRec.Appointment.location.id);
                appRecord.Cancellation_Details_Id__c = appointmentRec.Appointment.cancellation_details.id;
                appRecord.Care_Cloud_Comments__c = appointmentRec.Appointment.comments;
                appRecord.Referring_Physician_NPI__c = appointmentRec.Appointment.referring_physician_npi;
                appRecord.Visit_Reason_Id__c  = String.valueOf(appointmentRec.Appointment.visit_reason_id);
                appRecord.Care_Cloud_Patient_Id__c = appointmentRec.Appointment.patient.id;
                String start_time = appointmentRec.Appointment.start_time;
                DateTime dt = DateTime.ValueofGmt(start_time.replace('T', ' '));
                appRecord.Appointment_Date_Time__c  = dt.addHours(4);
                appRecord.Provider_Id__c = appointmentRec.Appointment.provider_id;
                appointExistIdList.add(appointmentRec.Appointment.id);
                appointmentList2Upsert.add(appRecord);
            } 
        }
		System.debug('::: AppointmentList2Upsert in execute = '+appointmentList2Upsert.size());
    }

    global void finish(Database.BatchableContext BC){
        
        System.debug('::: Inside the Finish statement');
        for(AppointmentJSONResponse appointment : appointmentList) {    
            if(!appointExistIdList.contains(appointment.Appointment.id)) {
                Appointment__c appRecord = new Appointment__c();
                appRecord.Care_Cloud_Appointment_Id__c  = appointment.Appointment.id;
                appRecord.Status__c = appointment.Appointment.appointment_status.Name;
                appRecord.Patient_Chart_Number__c = appointment.Appointment.patient.chart_number;
                appRecord.Location_Id__c = String.valueOf(appointment.Appointment.location.id);
                appRecord.Cancellation_Details_Id__c = appointment.Appointment.cancellation_details.id;
                appRecord.Care_Cloud_Comments__c = appointment.Appointment.comments;
                appRecord.Referring_Physician_NPI__c = appointment.Appointment.referring_physician_npi;
                appRecord.Visit_Reason_Id__c  = String.valueOf(appointment.Appointment.visit_reason_id);
                appRecord.Care_Cloud_Patient_Id__c = appointment.Appointment.patient.id;
                String start_time = appointment.Appointment.start_time;
                DateTime dt = DateTime.ValueofGmt(start_time.replace('T', ' '));
                appRecord.Appointment_Date_Time__c  = dt.addHours(4);
                appRecord.Provider_Id__c = appointment.Appointment.provider_id;
                appointmentList2Upsert.add(appRecord);  
            }                      
        }
        System.debug('::: AppointmentList2Upsert in finish = '+appointmentList2Upsert.size());   
        
        if(appointmentList2Upsert.size()>0) { 
            upsert appointmentList2Upsert;
        }
        
        // create log for appointments with no patient Id
        if (noPatientAppointmentId.size() > 0) {
            TransactionLogHandler.doHandleCustomException(
            	'No patient id found for few Appointments',
                String.join(new List<String>(noPatientAppointmentId), ','),
                'AppointmentSyncBatchCalloutDelta',
                'finish'
            );
        }
    }
}