force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason_Type__c</fullName>
    <formula>IF(CONTAINS(Visit_Reason__c, &quot;MD&quot;), &quot;MD&quot;, &quot;Not MD&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Reason Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteAppointmentsBatch.cls
public class DeleteAppointmentsBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Query all Appointment__c records
        return Database.getQueryLocator(
    'SELECT Id, Status__c, Provider_Name__c, Owner.Name, LastModifiedDate, Owner.Email, Care_Cloud_Appointment_Id__c ' +
    'FROM Appointment__c ' +
    'WHERE Visit_Reason_Type__c = \'MD\''
        ); }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        // Cast to the correct type
        List<Appointment__c> appointmentsToDelete = (List<Appointment__c>) scope;

        // Perform the delete
        delete appointmentsToDelete;
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Finished deleting appointment records.');
    }
}