force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Cancellation_Details_Id__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Details_Id__c</fullName>
    <label>Cancellation Details Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Appointment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Care Cloud Appointment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Comments__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Comments__c</fullName>
    <label>Care Cloud Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Care_Cloud_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Cloud_Patient_Id__c</fullName>
    <label>Care Cloud Patient Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient_Chart_Number__c.field-meta.xml
<CustomField>
    <fullName>Patient_Chart_Number__c</fullName>
    <label>Patient Chart Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Referring_Physician_NPI__c.field-meta.xml
<CustomField>
    <fullName>Referring_Physician_NPI__c</fullName>
    <label>Referring Physician NPI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Appointment_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Visit_Reason_Id__c.field-meta.xml
<CustomField>
    <fullName>Visit_Reason_Id__c</fullName>
    <label>Visit Reason Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carecloud_Setup__mdt/Carecloud_Setup__mdt.object-meta.xml
<CustomObject>
    <label>Carecloud Setup</label>
    <pluralLabel>Carecloud Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Carecloud_Setup__mdt/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CareCloudAppointmentService.cls
public with sharing class CareCloudAppointmentService {
    @InvocableMethod( label='Fetch Appointment Details' description='Fetch Appointment Details from CareCloud' category='Callout' )
    public static void getAppointment(List<InvocableParameters> requests) {
        System.debug('::: requests - '+requests);
        List<InvocableParameters> params = requests;
        Id accId = params[0].accId;
        Id intakeId = params[0].intakeId;
        
        getAppointmentDetailsFromCareCloud(accId, intakeId);        
    }

    @future( callout=true )
    public static void getAppointmentDetailsFromCareCloud(Id accId, Id intakeId) {
        try {
        List<Appointment__c> appointmentList2Insert  = new List<Appointment__c>();
        List<AppointmentJSONResponse> appointmentList = new List<AppointmentJSONResponse>();

        Carecloud_Setup__mdt CareCloudMdt = [Select MasterLabel, Refresh_Token__c FROM Carecloud_Setup__mdt LIMIT 1];
        String accessToken = CareCloudAuthConnection.fetchRefreshAccessToken(CareCloudMdt.Refresh_Token__c);
        System.debug('::: Access Toekn - '+accessToken);
        String patientId;
        
        String start_date = String.valueOf(Date.today()).removeEnd(' 00:00:00');
        String end_date = String.valueOf(Date.today().addDays(90)).removeEnd(' 00:00:00');
        
        //Get the Patient Id
        Account accRec = [SELECT Id, CareCloud_Patient_Id__c FROM Account where Id=: accId LIMIT 1];
        if(accRec!=null) patientId = accRec.CareCloud_Patient_Id__c;
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setTimeout(120000);
        //request.setEndpoint('https://api.carecloud.com/v2/appointments?patient_ids='+patientId);
        request.setEndpoint('https://api.carecloud.com/v2/appointments?start_date='+start_date+'&end_date='+end_date+'&patient_ids='+patientId);
        request.setMethod('GET');
        request.setHeader('Authorization', 'Bearer ' + accessToken);

        HttpResponse response = http.send(request);
        while(response.getStatusCode() == 302) {
            request.setEndpoint(response.getHeader('Location'));
            response = new Http().send(request);
        }
        //If Request is Successful, parse the response JSON
        System.debug('::: Response Body = '+response.getBody());
        
        appointmentList = AppointmentJSONResponse.parse(response.getBody());
        
        System.debug('::: appointmentList = '+appointmentList.size());
		Set<String> noPatientAppointmentId = new Set<String>();
        for(AppointmentJSONResponse appointment : appointmentList) {   
            Appointment__c appRecord = new Appointment__c();
            appRecord.Care_Cloud_Appointment_Id__c  = appointment.Appointment.id;
            appRecord.Status__c = appointment.Appointment.appointment_status.Name;
            appRecord.Patient_Chart_Number__c = appointment.Appointment.patient.chart_number;
            appRecord.Location_Id__c = String.valueOf(appointment.Appointment.location.id);
            appRecord.Cancellation_Details_Id__c = appointment.Appointment.cancellation_details.id;
            appRecord.Care_Cloud_Comments__c = appointment.Appointment.comments;
            appRecord.Referring_Physician_NPI__c = appointment.Appointment.referring_physician_npi;
            appRecord.Visit_Reason_Id__c  = String.valueOf(appointment.Appointment.visit_reason_id);
            appRecord.Patient__c = accRec.Id;
            appRecord.Intake__c = intakeId;
            appRecord.Care_Cloud_Patient_Id__c = appointment.Appointment.patient.id;
            String start_time = appointment.Appointment.start_time;
            DateTime dt = DateTime.ValueofGmt(start_time.replace('T', ' '));
            Integer timezoneDiff = Integer.valueOf(appointment.Appointment.start_time.split('-')[appointment.Appointment.start_time.split('-').size() - 1].split(':')[0]);
            appRecord.Appointment_Date_Time__c  = dt.addHours(timezoneDiff);
            appRecord.Provider_Id__c = appointment.Appointment.provider_id;
            
            if (String.isBlank(appointment.Appointment.patient.id)){
                noPatientAppointmentId.add(appointment.Appointment.id);
            }
            
            appointmentList2Insert.add(appRecord);                   
        }
        System.debug('::: appointmentList2Insert = '+appointmentList2Insert);
        if(appointmentList2Insert.size()>0) { 
            upsert appointmentList2Insert;
        }
        if (noPatientAppointmentId.size() > 0) {
            TransactionLogHandler.doHandleCustomException(
            	'No patient id found for few Appointments',
                String.join(new List<String>(noPatientAppointmentId), ','),
                'CareCloudAppointmentService',
                'getAppointmentDetailsFromCareCloud'
            );
        }
        }
        catch(Exception e){
            System.debug('Execetion : ' + e.getMessage());
        }
    }
    
    public class PatientResponse {
        public String patient;
    }

    public class InvocableParameters {
        @InvocableVariable(required = true)
        public Id accId;

        @InvocableVariable(required = true)
        public Id intakeId;
    } 
}