force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Custom_Message__c.field-meta.xml
<CustomField>
    <fullName>Custom_Message__c</fullName>
    <label>Custom Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>60768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Error_Log_Time__c.field-meta.xml
<CustomField>
    <fullName>Error_Log_Time__c</fullName>
    <label>Error Log Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Review InProgress</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionLogHandler.cls
/*
    @Created Date : 28-April-2022
    @Description : Capture Log record if there is any Error while processing 
*/
public class TransactionLogHandler {
    public static void doHandleException(System.Exception ex, String className, String methodName) {
        Transaction_Log__c logRecord = new Transaction_Log__c(
            Error_Log__c = ex.getStackTraceString() +'<br/>' + ex.getMessage() + '<br/>' + ex.getCause() +' <br/>'+ ex.getTypeName(),
            Error_Log_Time__c = System.Now(),
            Status__c = 'New',
            Class_Name__c = className,
            Method_Name__c = methodName
        );

        if(Schema.sObjectType.Transaction_Log__c.isCreateable()){
            insert logRecord;
        }
    }
    
    public static void doHandleCustomException(System.Exception ex, String customMsg, String className, String methodName) {
        Transaction_Log__c logRecord = new Transaction_Log__c(
            Error_Log__c = ex.getStackTraceString() +'<br/>' + ex.getMessage() + '<br/>' + ex.getCause() +' <br/>'+ ex.getTypeName(),
            Custom_Message__c = customMsg,
            Error_Log_Time__c = System.Now(),
            Status__c = 'New',
            Class_Name__c = className,
            Method_Name__c = methodName
        );

        if(Schema.sObjectType.Transaction_Log__c.isCreateable()){
            insert logRecord;
        }
    }
    
    public static void doHandleCustomException(String customLog, String customMsg, String className, String methodName) {
        Transaction_Log__c logRecord = new Transaction_Log__c(
            Error_Log__c = customLog,
            Custom_Message__c = customMsg,
            Error_Log_Time__c = System.Now(),
            Status__c = 'New',
            Class_Name__c = className,
            Method_Name__c = methodName
        );

        if(Schema.sObjectType.Transaction_Log__c.isCreateable()){
            insert logRecord;
        }
    }
}