force-app/main/default/objects/Hz_Horizon_Charges__c/Hz_Horizon_Charges__c.object-meta.xml
<CustomObject>
    <label>Horizon Charge</label>
    <nameField>
        <displayFormat>Hz-{0000}</displayFormat>
        <label>Horizon Health Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Horizon Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/FH_Geozip__c.field-meta.xml
<CustomField>
    <fullName>FH_Geozip__c</fullName>
    <formula>LEFT(Geozip__c, 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FH Geozip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Geozip__c.field-meta.xml
<CustomField>
    <fullName>Geozip__c</fullName>
    <label>Geozip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Aggregate_Allowance__c.field-meta.xml
<CustomField>
    <fullName>Hz_Aggregate_Allowance__c</fullName>
    <formula>TEXT(Hz_Insurance_Plan__r.Aggregate_Allowance__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aggregate Allowance</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Allowance_Percentage_Number__c.field-meta.xml
<CustomField>
    <fullName>Hz_Allowance_Percentage_Number__c</fullName>
    <formula>Hz_Insurance_Plan__r.Allowance_Percentage_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allowance Percentage Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Amount__c.field-meta.xml
<CustomField>
    <fullName>Hz_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_DOS__c.field-meta.xml
<CustomField>
    <fullName>Hz_DOS__c</fullName>
    <label>DOS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Expected_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Hz_Expected_Reimbursement__c</fullName>
    <label>Expected Reimbursement</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_fee_schedule__c.field-meta.xml
<CustomField>
    <fullName>Hz_fee_schedule__c</fullName>
    <formula>IF(
  OR(
    TEXT(Hz_VOB_Case__r.VOB_Type__c) = &apos;Reverification&apos;,
    TEXT(Hz_VOB_Case__r.VOB_Type__c) = &apos;Major Med&apos;
  ),
  TEXT(Hz_Insurance_Plan__r.Fee_Schedule__c),
  NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fee Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Hz_Insurance_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>Insurance_Plan__c</referenceTo>
    <relationshipName>Horizon_Healths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Hz_Location_Id__c</fullName>
    <label>Location Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>Hz_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Horizon_Healths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Payer_Id__c.field-meta.xml
<CustomField>
    <fullName>Hz_Payer_Id__c</fullName>
    <label>Payer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>Hz_Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Hz_Provider_Id__c</fullName>
    <label>Provider Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_Review_Assessment_Notes__c.field-meta.xml
<CustomField>
    <fullName>Hz_Review_Assessment_Notes__c</fullName>
    <label>Review Assessment Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Hz_VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>Hz_VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Horizon_Healths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hz_Horizon_Charges__c/fields/Medicare_Geozip__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Geozip__c</fullName>
    <formula>LEFT(Geozip__c, 5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medicare Geozip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Daily_Chiro_Capitated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Daily_Chiro_Capitated_Fee__c</fullName>
    <label>Daily Chiro Capitated Fee</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Daily_OT_Capitated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Daily_OT_Capitated_Fee__c</fullName>
    <label>Daily OT Capitated Fee</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Daily_PT_Capitated_Fee__c.field-meta.xml
<CustomField>
    <fullName>Daily_PT_Capitated_Fee__c</fullName>
    <label>Daily PT Capitated Fee</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HorizonChargeBatch.cls
public class HorizonChargeBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Hz_Patient_Account__c, Hz_DOS__c, Hz_Insurance_Plan__c, Hz_VOB_Case__c, Hz_Provider_Id__c, Hz_Aggregate_Allowance__c,
                   Hz_Fee_Schedule__c, Hz_Allowance_Percentage_Number__c, Geozip__c, Hz_Procedure_Code__c, Hz_Payer_Id__c, FH_Geozip__c,
                   Medicare_Geozip__c, Hz_Location_Id__c, Hz_Review_Assessment_Notes__c, Hz_Insurance_Plan__r.Daily_OT_Capitated_Fee__c,
                   Hz_Insurance_Plan__r.Daily_Chiro_Capitated_Fee__c, Hz_Insurance_Plan__r.Daily_PT_Capitated_Fee__c, Hz_Amount__c, 
                   Hz_Expected_Reimbursement__c, CreatedDate, Provider_Specialty__c	
            FROM Hz_Horizon_Charges__c
            WHERE Hz_Patient_Account__c != null 
        ]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Hz_Horizon_Charges__c> chargeList = new List<Hz_Horizon_Charges__c>();
        Map<Id, Decimal> originalReimbursementMap = new Map<Id, Decimal>();
        
        // Cast SObjects and store original Hz_Expected_Reimbursement__c values
        for (SObject sObj : scope) {
            Hz_Horizon_Charges__c charge = (Hz_Horizon_Charges__c) sObj;
            chargeList.add(charge);
            originalReimbursementMap.put(charge.Id, charge.Hz_Expected_Reimbursement__c);
        }
        System.debug('Starting batch with ' + chargeList.size() + ' charges for processing');

        // Process charges through HorizonChargeHandler first (no filtering)
        if (!chargeList.isEmpty()) {
            HorizonChargeHandler.processCharges(chargeList);
            System.debug('After HorizonChargeHandler, all ' + chargeList.size() + ' charges remain for reimbursement processing');
            
            // Now apply if-else logic for handlers that update Hz_Expected_Reimbursement__c
            if (!chargeList.isEmpty()) {
                // 1. HorizonChargeReimbursementHandler
                HorizonChargeReimbursementHandler.processReimbursements(chargeList);
                chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                System.debug('After HorizonChargeReimbursementHandler, ' + chargeList.size() + ' charges remain');

                if (!chargeList.isEmpty()) {
                    // 2. HorizonChargeFHAndMedicareHandler
                    HorizonChargeFHAndMedicareHandler.processCharges(chargeList);
                    chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                    System.debug('After HorizonChargeFHAndMedicareHandler, ' + chargeList.size() + ' charges remain');

                    if (!chargeList.isEmpty()) {
                        // 3. HorizonChargeNationalHandler
                        HorizonChargeNationalHandler.processCharges(chargeList);
                        chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                        System.debug('After HorizonChargeNationalHandler, ' + chargeList.size() + ' charges remain');

                        if (!chargeList.isEmpty()) {
                            // 4. HorizonChargeMedicares
                            HorizonChargeMedicares.processCharges(chargeList);
                            chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                            System.debug('After HorizonChargeMedicares, ' + chargeList.size() + ' charges remain');

                            if (!chargeList.isEmpty()) {
                                // 5. ReviewAssessmentNotesHandler
                                ReviewAssessmentNotesHandler.updateReviewNotes(chargeList);
                                chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                                System.debug('After ReviewAssessmentNotesHandler, ' + chargeList.size() + ' charges remain');

                                if (!chargeList.isEmpty()) {
                                    // 6. MedicareOnepointTwo
                                    MedicareOnepointTwo.processCharges(chargeList);
                                    chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                                    System.debug('After MedicareOnepointTwo, ' + chargeList.size() + ' charges remain');

                                    if (!chargeList.isEmpty()) {
                                        // 7. FHClaimNumber
                                        FHClaimNumber.processCharges(chargeList);
                                        chargeList = filterUnupdatedCharges(chargeList, originalReimbursementMap);
                                        System.debug('After FHClaimNumber, ' + chargeList.size() + ' charges remain');

                                        if (!chargeList.isEmpty()) {
                                            // 8. HorizonNorthHandler
                                            HorizonNorthHandler.processCharges(chargeList);
                                            System.debug('After HorizonNorthHandler, processing complete');
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    // Helper method to filter out charges that have been updated
    private List<Hz_Horizon_Charges__c> filterUnupdatedCharges(List<Hz_Horizon_Charges__c> charges, 
                                                              Map<Id, Decimal> originalReimbursementMap) {
        List<Hz_Horizon_Charges__c> unupdatedCharges = new List<Hz_Horizon_Charges__c>();
        for (Hz_Horizon_Charges__c charge : charges) {
            Decimal originalReimbursement = originalReimbursementMap.get(charge.Id);
            // Check if Hz_Expected_Reimbursement__c has changed
            if (charge.Hz_Expected_Reimbursement__c != originalReimbursement) {
                System.debug('Charge Id=' + charge.Id + ' updated with Hz_Expected_Reimbursement__c=' + 
                             charge.Hz_Expected_Reimbursement__c);
            } else {
                unupdatedCharges.add(charge);
            }
        }
        return unupdatedCharges;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch Finished.');
    }
}