force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <displayFormat>Coverage-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage__c/fields/In_Network_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Deductible_Met__c</fullName>
    <label>In Network Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/In_Network_Family_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Family_Deductible_Met__c</fullName>
    <label>In Network Family Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/In_Network_Out_of_Pocket_Max_Met__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Out_of_Pocket_Max_Met__c</fullName>
    <label>In Network Out of Pocket Max Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>Insurance_Plan__c</referenceTo>
    <relationshipName>Patient_Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Out_of_Network_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Deductible_Met__c</fullName>
    <label>Out of Network Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Out_of_Network_Family_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Family_Deductible_Met__c</fullName>
    <label>Out of Network Family Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Out_of_Network_Out_of_Pocket_Max_Met__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Out_of_Pocket_Max_Met__c</fullName>
    <label>Out of Network Out of Pocket Max Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Acupuncture_Visits_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Acupuncture_Visits_Allowed__c</fullName>
    <label>Acupuncture Visits Allowed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Acupuncture_Visits_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Acupuncture_Visits_To_Date__c</fullName>
    <label>Acupuncture Visits To Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Aggregate_Allowance__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Allowance__c</fullName>
    <label>Aggregate Allowance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Allowance_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Allowance_Percentage__c</fullName>
    <label>Allowance Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Acupuncture__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Acupuncture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Acupuncture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_DME__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_DME__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for DME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_OT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for OT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_Procedures__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_Procedures__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for Procedures</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Authorization_Required_for_PT__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Required_for_PT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authorization Required for PT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Length__c.field-meta.xml
<CustomField>
    <fullName>Call_Length__c</fullName>
    <label>Call Length</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Can_patient_treat_at_ASC__c.field-meta.xml
<CustomField>
    <fullName>Can_patient_treat_at_ASC__c</fullName>
    <label>Can Patient Treat at ASC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_Allowed__c</fullName>
    <label>Chiro Visits Allowed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_Combined__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_Combined__c</fullName>
    <label>Chiro Visits Combined</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No_N_A</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiro_Visits_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Chiro_Visits_To_Date__c</fullName>
    <label>Chiro Visits To Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Chiropractic_Benefits_Notes__c.field-meta.xml
<CustomField>
    <fullName>Chiropractic_Benefits_Notes__c</fullName>
    <label>Chiropractic Benefits Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Date_of_Accident__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Accident__c</fullName>
    <label>Date of Accident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Fee_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Fee_Schedule__c</fullName>
    <label>Fee Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fee_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Acupuncture_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Acupuncture_Authorization__c</fullName>
    <label>How to Obtain Acupuncture Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Family_Deductible__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Family_Deductible__c</fullName>
    <label>In Network Family Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Individual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Individual_Deductible__c</fullName>
    <label>In Network Individual Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Out_of_Pocket_Max__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Out_of_Pocket_Max__c</fullName>
    <label>In Network Out of Pocket Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Insurance_Company_Representative__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Representative__c</fullName>
    <label>Insurance Company Representative</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_ACU__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_ACU__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for ACU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_OT__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for OT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_PT__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_PT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for PT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Occupation_Therapy_Visits_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Therapy_Visits_Allowed__c</fullName>
    <label>Occupation Therapy Visits Allowed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Occupational_Therapy_Visits_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Occupational_Therapy_Visits_To_Date__c</fullName>
    <label>Occupational Therapy Visits To Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Out_of_Network_Family_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Family_Deductible__c</fullName>
    <label>Out of Network Family Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Out_of_Network_Individual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Individual_Deductible__c</fullName>
    <label>Out of Network Individual Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Out_of_Network_Out_of_Pocket_Max__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Out_of_Pocket_Max__c</fullName>
    <label>Out of Network Out of Pocket Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Physical_Therapy_Visits_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Physical_Therapy_Visits_Allowed__c</fullName>
    <label>Physical Therapy Visits Allowed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Physical_Therapy_Visits_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Physical_Therapy_Visits_To_Date__c</fullName>
    <label>Physical Therapy Visits To Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Secondary_Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Plan_Effective_Date__c</fullName>
    <label>Secondary Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Start_of_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_of_Plan_Year__c</fullName>
    <label>Start of Plan Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeductibleAccumulationFormControllerTest.cls
@IsTest
public class DeductibleAccumulationFormControllerTest {
   @IsTest
    static void testDeductibleAccumulationFormController() {
         Account acc = new Account(Name ='Test');
        insert acc;
        
        Case cs = new Case();
        cs.Status = 'New';
        cs.Patient_Name__c = 'Test Patient';
        cs.Patient_Date_of_Birth__c = System.today();
       
        cs.Subject = 'test subject';
        cs.PIP_Date_of_Loss__c = System.today();
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Authorization_Required_for_Acupuncture__c = true;
        ins.Authorization_Required_for_DME__c = true;
        ins.Authorization_Required_for_OT__c = true;
        ins.Authorization_Required_for_Procedures__c = true;
        ins.Authorization_Required_for_PT__c = true;
        
        ins.VOB_Case__c = cs.Id;
        ins.Plan_Effective_Date__c = System.today();
        ins.Start_of_Plan_Year__c = System.today();
        ins.Secondary_Plan_Effective_Date__c = System.today();
        ins.Date_of_Accident__c = System.today();
        insert ins;
        
        
        Coverage__c cov = new Coverage__c();
        cov.Insurance_Plan__c = ins.Id;
        cov.In_Network_Deductible_Met__c =  10000000; 
        cov.In_Network_Family_Deductible_Met__c= 100000000 ;
        cov.In_Network_Out_of_Pocket_Max_Met__c= 20000000;
        cov.Out_of_Network_Deductible_Met__c= 300000000;
        cov.Out_of_Network_Family_Deductible_Met__c= 1000000;
        cov.Out_of_Network_Out_of_Pocket_Max_Met__c= 200000000;
        insert cov;
        
        Test.startTest();
        
        List<Insurance_Plan__c> plans = [
            SELECT
             Id,
            RecordType.Name,
            Patient_Name__c,
            
            Patient_Date_of_Birth__c,
            
            In_Network_Individual_Deductible__c,
            Out_of_Network_Individual_Deductible__c,
            In_Network_Family_Deductible__c,
            Out_of_Network_Family_Deductible__c,
            In_Network_Out_of_Pocket_Max__c,
            Out_of_Network_Out_of_Pocket_Max__c,
            Fee_Schedule__c,
            Aggregate_Allowance__c,
            Allowance_Percentage__c,
            Chiro_Visits_Allowed__c,
            Chiro_Visits_To_Date__c,
            Physical_Therapy_Visits_Allowed__c,
            Physical_Therapy_Visits_To_Date__c,
            Occupation_Therapy_Visits_Allowed__c,
            Occupational_Therapy_Visits_To_Date__c,
            Acupuncture_Visits_Allowed__c,
            Acupuncture_Visits_To_Date__c,
            Medical_Necessity_Exemption_for_Chiro__c,
            Medical_Necessity_Exemption_for_PT__c,
            Medical_Necessity_Exemption_for_OT__c,
            Medical_Necessity_Exemption_for_ACU__c,
            Insurance_Company_Representative__c,
            Call_Reference_Number__c,
            Call_Length__c,
            Chiropractic_Benefits_Notes__c,
            Occupational_Therapy_Benefits_Notes__c,
            Physical_Therapy_Benefits_Notes__c,
            Acupuncture_Therapy_Benefits_Notes__c
            FROM Insurance_Plan__c LIMIT 1 ];
        
        List<Case> caseLst = [Select Id, 
                         Primary_Insurance__c,
                      Patient_VOB__c,
                      Patient_VOB__r.Name,
                      Patient_VOB__r.Date_of_Birth__c,
                      Patient_Name__c,
                      Patient_Date_of_Birth__c,
                     
                      PIP_Insurance_Company__c
                        FROM Case ];
        List<Coverage__c> coverages = [
            SELECT 
            In_Network_Deductible_Met__c,
            In_Network_Family_Deductible_Met__c,
            In_Network_Family_Out_of_Pocket__c,
            In_Network_Out_of_Pocket_Max_Met__c,
            Out_of_Network_Deductible_Met__c,
            Out_of_Network_Family_Deductible_Met__c,
            Out_of_Network_Out_of_Pocket_Max_Met__c,
            Insurance_Plan__c
            FROM
            Coverage__c
        ];
        
        PageReference vfPage = Page.DeductibleAccumulationFormPDF;
        Test.setCurrentPage(vfPage);
        ApexPages.currentPage().getParameters().put('id',caseLst[0].Id);
        DeductibleAccumulationFormController insp = new DeductibleAccumulationFormController();
        
        Test.stopTest();
    }
     @IsTest
    static void testDeductibleAccumulationFormController2() {
         Account acc = new Account(Name ='Test');
        insert acc;
        
        Case cs = new Case();
        cs.Status = 'New';
        cs.Patient_Name__c = 'Test Patient';
        cs.Patient_Date_of_Birth__c = System.today();
       
        cs.Subject = 'test subject';
        cs.PIP_Date_of_Loss__c = System.today();
        insert cs;
        
        Insurance_Plan__c ins = new Insurance_Plan__c();
        ins.Patient_Name__c = 'Test Name';
        ins.Chiro_Visits_Combined__c = 'yes';
        ins.Authorization_Required_for_Chiro__c = true;
        ins.How_to_Obtain_Acupuncture_Authorization__c = '8457598255';
        ins.Can_patient_treat_at_ASC__c = 'Yes'; 
        ins.Authorization_Required_for_Acupuncture__c = true;
        ins.Authorization_Required_for_DME__c = true;
        ins.Authorization_Required_for_OT__c = true;
        ins.Authorization_Required_for_Procedures__c = true;
        ins.Authorization_Required_for_PT__c = true;
        ins.Medical_Necessity_Exemption_for_Chiro__c = true;
        ins.Medical_Necessity_Exemption_for_PT__c = true;
        ins.Medical_Necessity_Exemption_for_OT__c = true;  
        ins.Medical_Necessity_Exemption_for_ACU__c = true;
        ins.VOB_Case__c = cs.Id;
        ins.Plan_Effective_Date__c = System.today();
        ins.Start_of_Plan_Year__c = System.today();
        ins.Secondary_Plan_Effective_Date__c = System.today();
        ins.Date_of_Accident__c = System.today();
        insert ins;
        
        
        Coverage__c cov = new Coverage__c();
        cov.Insurance_Plan__c = ins.Id;
        cov.In_Network_Deductible_Met__c =  10000000; 
        cov.In_Network_Family_Deductible_Met__c= 100000000 ;
        cov.In_Network_Out_of_Pocket_Max_Met__c= 20000000;
        cov.Out_of_Network_Deductible_Met__c= 300000000;
        cov.Out_of_Network_Family_Deductible_Met__c= 1000000;
        cov.Out_of_Network_Out_of_Pocket_Max_Met__c= 200000000;
        insert cov;
        
        Test.startTest();
        
        List<Insurance_Plan__c> plans = [
            SELECT
             Id,
            RecordType.Name,
            Patient_Name__c,
            
            Patient_Date_of_Birth__c,
            
            In_Network_Individual_Deductible__c,
            Out_of_Network_Individual_Deductible__c,
            In_Network_Family_Deductible__c,
            Out_of_Network_Family_Deductible__c,
            In_Network_Out_of_Pocket_Max__c,
            Out_of_Network_Out_of_Pocket_Max__c,
            Fee_Schedule__c,
            Aggregate_Allowance__c,
            Allowance_Percentage__c,
            Chiro_Visits_Allowed__c,
            Chiro_Visits_To_Date__c,
            Physical_Therapy_Visits_Allowed__c,
            Physical_Therapy_Visits_To_Date__c,
            Occupation_Therapy_Visits_Allowed__c,
            Occupational_Therapy_Visits_To_Date__c,
            Acupuncture_Visits_Allowed__c,
            Acupuncture_Visits_To_Date__c,
            Medical_Necessity_Exemption_for_Chiro__c,
            Medical_Necessity_Exemption_for_PT__c,
            Medical_Necessity_Exemption_for_OT__c,
            Medical_Necessity_Exemption_for_ACU__c,
            Insurance_Company_Representative__c,
            Call_Reference_Number__c,
            Call_Length__c,
            Chiropractic_Benefits_Notes__c,
            Occupational_Therapy_Benefits_Notes__c,
            Physical_Therapy_Benefits_Notes__c,
            Acupuncture_Therapy_Benefits_Notes__c
            FROM Insurance_Plan__c LIMIT 1 ];
        
        List<Case> caseLst = [Select Id, 
                         Primary_Insurance__c,
                      Patient_VOB__c,
                      Patient_VOB__r.Name,
                      Patient_VOB__r.Date_of_Birth__c,
                      Patient_Name__c,
                      Patient_Date_of_Birth__c,
                     
                      PIP_Insurance_Company__c
                        FROM Case ];
        List<Coverage__c> coverages = [
            SELECT 
            In_Network_Deductible_Met__c,
            In_Network_Family_Deductible_Met__c,
            In_Network_Family_Out_of_Pocket__c,
            In_Network_Out_of_Pocket_Max_Met__c,
            Out_of_Network_Deductible_Met__c,
            Out_of_Network_Family_Deductible_Met__c,
            Out_of_Network_Out_of_Pocket_Max_Met__c,
            Insurance_Plan__c
            FROM
            Coverage__c
        ];
        
        PageReference vfPage = Page.DeductibleAccumulationFormPDF;
        Test.setCurrentPage(vfPage);
        ApexPages.currentPage().getParameters().put('id',caseLst[0].Id);
        DeductibleAccumulationFormController insp = new DeductibleAccumulationFormController();
        
        Test.stopTest();
        
       
    }
 

}