force-app/main/default/objects/Coverage__c/Coverage__c.object-meta.xml
<CustomObject>
    <label>Coverage</label>
    <nameField>
        <displayFormat>Coverage-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage__c/fields/In_Network_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Deductible_Met__c</fullName>
    <label>In Network Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/In_Network_Out_of_Pocket_Max_Met__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Out_of_Pocket_Max_Met__c</fullName>
    <label>In Network Out of Pocket Max Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>Insurance_Plan__c</referenceTo>
    <relationshipName>Patient_Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Out_of_Network_Deductible_Met__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Deductible_Met__c</fullName>
    <label>Out of Network Deductible Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Coverage__c/fields/Out_of_Network_Out_of_Pocket_Max_Met__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Out_of_Pocket_Max_Met__c</fullName>
    <label>Out of Network Out of Pocket Max Met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/Insurance_Plan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <displayFormat>IP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Plan__c/fields/Aggregate_Allowance__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Allowance__c</fullName>
    <label>Aggregate Allowance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Allowance_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Allowance_Percentage__c</fullName>
    <label>Allowance Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Ambulatory_Surgery_Center_Covered__c.field-meta.xml
<CustomField>
    <fullName>Ambulatory_Surgery_Center_Covered__c</fullName>
    <label>Ambulatory Surgery Center Covered</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Call_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Reference_Number__c</fullName>
    <label>Call Reference Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Fee_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Fee_Schedule__c</fullName>
    <label>Fee Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fee_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/How_to_Obtain_Procedure_Authorization__c.field-meta.xml
<CustomField>
    <fullName>How_to_Obtain_Procedure_Authorization__c</fullName>
    <label>How to Obtain Procedure Authorization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Co_Insurance_Percentage__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Co_Insurance_Percentage__c</fullName>
    <label>In Network Co-Insurance Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Individual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Individual_Deductible__c</fullName>
    <label>In Network Individual Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/In_Network_Out_of_Pocket_Max__c.field-meta.xml
<CustomField>
    <fullName>In_Network_Out_of_Pocket_Max__c</fullName>
    <label>In Network Out of Pocket Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Insurance_Company_Representative__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company_Representative__c</fullName>
    <label>Insurance Company Representative</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Insurance_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Insurance_ID_Number__c</fullName>
    <label>Insurance ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_ACU__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_ACU__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for ACU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_Chiro__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_Chiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for Chiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_OT__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for OT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Medical_Necessity_Exemption_for_PT__c.field-meta.xml
<CustomField>
    <fullName>Medical_Necessity_Exemption_for_PT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Necessity Exemption for PT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Out_of_Network_Individual_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Individual_Deductible__c</fullName>
    <label>Out of Network Individual Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Out_of_Network_Out_of_Pocket_Max__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Network_Out_of_Pocket_Max__c</fullName>
    <label>Out of Network Out of Pocket Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Date_Of_Birth__c</fullName>
    <label>Patient Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/Surgical_Verification_Notes__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Verification_Notes__c</fullName>
    <label>Surgical Verification Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Plan__c/fields/VOB_Case__c.field-meta.xml
<CustomField>
    <fullName>VOB_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOB Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Insurance Plans</relationshipLabel>
    <relationshipName>Insurance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/Insurance_Verification__c.object-meta.xml
<CustomObject>
    <label>Insurance/Claim Information</label>
    <nameField>
        <displayFormat>IV-{000000000}</displayFormat>
        <label>Insurance/Claim Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance/Claim Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Verification__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <formula>IF( NOT( ISBLANK(Potential_Patient__r.Lead_Date_of_Birth__c) ) ,Potential_Patient__r.Lead_Date_of_Birth__c, Patient__r.Date_of_Birth__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Verification__c/fields/Primary_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Primary_Insurance__c</fullName>
    <label>Primary Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Health_Insurance_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SurgicalVerificationController.cls
public class SurgicalVerificationController {
     public Case caseRecord{get;set;}
    public Insurance_Plan__c insurancePlanRecord { get; private set; }
    //public Insurance_Verification__c ic { get; private set;}
    public Coverage__c coverage {get; private set;}
   
    public String patientName{get;set;}
    public String patientDOB{get;set;}
     public String patientDOBb{get;set;}
     public String procedureDate{get;set;}
   
    
    public String todaydate{get;set;}
    
     public SurgicalVerificationController() {
        this.insurancePlanRecord = new Insurance_Plan__c();
        //this.coverage = new Coverage__c();
    
        String csId = ApexPages.currentPage().getParameters().get('id');
        
        caseRecord = [Select Id, 
                      Primary_Insurance__c,
                      Patient_VOB__c,
                      Patient_VOB__r.Name,
                      Patient_VOB__r.Date_of_Birth__c,
                      Patient_Name__c,
                      Patient_Date_of_Birth__c,
                      PIP_Insurance_Company__c,
                      
                      Procedure_Date__c,
                      Surgical_Provider__c,
                      Inpatient_Outpatient__c,
                      DX_Codes_Text__c,CPT_Codes_Text__c,
                      Member_ID__c
                     
                      FROM Case where Id=:csId];
        if(caseRecord.Patient_Name__c != null) {
            patientName = caseRecord.Patient_Name__c;
        } else if(caseRecord.Patient_VOB__r.Name != null) {
            patientName = caseRecord.Patient_VOB__r.Name;
        } 
        
        if(caseRecord.Patient_Date_of_Birth__c != null) {
            patientDOB = caseRecord.Patient_Date_of_Birth__c.format();
        } else if(caseRecord.Patient_VOB__r.Date_of_Birth__c != null) {
            patientDOB = caseRecord.Patient_VOB__r.Date_of_Birth__c.format();
        }
         if(caseRecord.Procedure_Date__c != null) {
            procedureDate = caseRecord.Procedure_Date__c.format(); 
         }
         
        
        todaydate = Date.today().format();
        
        System.debug('::: Patient name and dob - '+patientName+' and '+patientDOB);
        List<Insurance_Plan__c> plans = [
            SELECT Id,
            RecordType.Name,
            Patient_Name__c,
            
            Medical_Necessity_Exemption_for_Chiro__c,
            Medical_Necessity_Exemption_for_PT__c,
            Medical_Necessity_Exemption_for_OT__c,
            Medical_Necessity_Exemption_for_ACU__c,
            Patient_Date_of_Birth__c,
            Insurance_ID_Number__c,
            
            In_Network_Co_Insurance_Percentage__c,
            In_Network_Individual_Deductible__c,
            In_Network_Out_of_Pocket_Max__c,
            Out_of_Network_Individual_Deductible__c,
            Out_of_Network_Out_of_Pocket_Max__c,
            How_to_Obtain_Procedure_Authorization__c,
            Ambulatory_Surgery_Center_Covered__c,
            Fee_Schedule__c,
            Aggregate_Allowance__c,
            Allowance_Percentage__c,
            Call_Reference_Number__c,
            Insurance_Company_Representative__c,
            Surgical_Verification_Notes__c
            
            FROM
            Insurance_Plan__c
            WHERE
            VOB_Case__c = :csId
            order by createddate DESC
            LIMIT 1
        ];
        
        if (plans != null && plans.size() > 0) {
            system.debug(plans);
            this.insurancePlanRecord = plans[0];
        
           
            List<Coverage__c> coverages = [
                SELECT 
                In_Network_Deductible_Met__c,
                In_Network_Out_of_Pocket_Max_Met__c,
                Out_of_Network_Deductible_Met__c,
                Out_of_Network_Out_of_Pocket_Max_Met__c
                FROM
                Coverage__c
                WHERE
                Insurance_Plan__c = :plans[0].Id
            ];
            if (coverages != null && coverages.size() > 0) {
                this.coverage = coverages[0];
            }
           /*  if(insurancePlanRecord.Patient_Date_of_Birth__c != null) {
            patientDOBb = insurancePlanRecord.Patient_Date_of_Birth__c.format();
        }*/
            
        }
         

    }

}